/*
 * generated by Xtext 2.21.0
 */
package org.xtext.svjd.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.svjd.VideoMontageRuntimeModule;
import org.xtext.svjd.VideoMontageStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class VideoMontageIdeSetup extends VideoMontageStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new VideoMontageRuntimeModule(), new VideoMontageIdeModule()));
	}
	
}
