/*
 * generated by Xtext 2.21.0
 */
package org.xtext.svjd;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class VideoMontageStandaloneSetup extends VideoMontageStandaloneSetupGenerated {

	public static void doSetup() {
		new VideoMontageStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
