/**
 * generated by Xtext 2.24.0
 */
package org.xtext.svjd.videoMontageSVJD.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.svjd.videoMontageSVJD.VideoElement;
import org.xtext.svjd.videoMontageSVJD.VideoMontageSVJDPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Video Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class VideoElementImpl extends ElementImpl implements VideoElement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VideoElementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return VideoMontageSVJDPackage.Literals.VIDEO_ELEMENT;
  }

} //VideoElementImpl
