/*
 * generated by Xtext 2.21.0
 */
package org.xtext.svjd.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class VideoMontageGrammarAccess extends AbstractGrammarElementFinder {
	
	public class MovieElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.svjd.VideoMontage.Movie");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMovieKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTitleAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTitleEStringParserRuleCall_1_0 = (RuleCall)cTitleAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cVideoelementAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cVideoelementVideoElementParserRuleCall_3_0 = (RuleCall)cVideoelementAssignment_3.eContents().get(0);
		private final Assignment cVideoelementAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cVideoelementVideoElementParserRuleCall_4_0 = (RuleCall)cVideoelementAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Assignment cAudioelementAssignment_5_0 = (Assignment)cGroup_5.eContents().get(0);
		private final RuleCall cAudioelementAudioElementParserRuleCall_5_0_0 = (RuleCall)cAudioelementAssignment_5_0.eContents().get(0);
		private final Assignment cAudioelementAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cAudioelementAudioElementParserRuleCall_5_1_0 = (RuleCall)cAudioelementAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Assignment cSubtitleAssignment_6_0 = (Assignment)cGroup_6.eContents().get(0);
		private final RuleCall cSubtitleSubtitleParserRuleCall_6_0_0 = (RuleCall)cSubtitleAssignment_6_0.eContents().get(0);
		private final Assignment cSubtitleAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cSubtitleSubtitleParserRuleCall_6_1_0 = (RuleCall)cSubtitleAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Movie:
		//	'Movie' title=EString
		//	'{'
		//	videoelement+=VideoElement videoelement+=VideoElement* (audioelement+=AudioElement audioelement+=AudioElement*)?
		//	(subtitle+=Subtitle subtitle+=Subtitle*)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Movie' title=EString '{' videoelement+=VideoElement videoelement+=VideoElement* (audioelement+=AudioElement
		//audioelement+=AudioElement*)? (subtitle+=Subtitle subtitle+=Subtitle*)? '}'
		public Group getGroup() { return cGroup; }
		
		//'Movie'
		public Keyword getMovieKeyword_0() { return cMovieKeyword_0; }
		
		//title=EString
		public Assignment getTitleAssignment_1() { return cTitleAssignment_1; }
		
		//EString
		public RuleCall getTitleEStringParserRuleCall_1_0() { return cTitleEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//videoelement+=VideoElement
		public Assignment getVideoelementAssignment_3() { return cVideoelementAssignment_3; }
		
		//VideoElement
		public RuleCall getVideoelementVideoElementParserRuleCall_3_0() { return cVideoelementVideoElementParserRuleCall_3_0; }
		
		//videoelement+=VideoElement*
		public Assignment getVideoelementAssignment_4() { return cVideoelementAssignment_4; }
		
		//VideoElement
		public RuleCall getVideoelementVideoElementParserRuleCall_4_0() { return cVideoelementVideoElementParserRuleCall_4_0; }
		
		//(audioelement+=AudioElement audioelement+=AudioElement*)?
		public Group getGroup_5() { return cGroup_5; }
		
		//audioelement+=AudioElement
		public Assignment getAudioelementAssignment_5_0() { return cAudioelementAssignment_5_0; }
		
		//AudioElement
		public RuleCall getAudioelementAudioElementParserRuleCall_5_0_0() { return cAudioelementAudioElementParserRuleCall_5_0_0; }
		
		//audioelement+=AudioElement*
		public Assignment getAudioelementAssignment_5_1() { return cAudioelementAssignment_5_1; }
		
		//AudioElement
		public RuleCall getAudioelementAudioElementParserRuleCall_5_1_0() { return cAudioelementAudioElementParserRuleCall_5_1_0; }
		
		//(subtitle+=Subtitle subtitle+=Subtitle*)?
		public Group getGroup_6() { return cGroup_6; }
		
		//subtitle+=Subtitle
		public Assignment getSubtitleAssignment_6_0() { return cSubtitleAssignment_6_0; }
		
		//Subtitle
		public RuleCall getSubtitleSubtitleParserRuleCall_6_0_0() { return cSubtitleSubtitleParserRuleCall_6_0_0; }
		
		//subtitle+=Subtitle*
		public Assignment getSubtitleAssignment_6_1() { return cSubtitleAssignment_6_1; }
		
		//Subtitle
		public RuleCall getSubtitleSubtitleParserRuleCall_6_1_0() { return cSubtitleSubtitleParserRuleCall_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class AudioElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.svjd.VideoMontage.AudioElement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAudioElementKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final RuleCall cAudioParserRuleCall_1_0 = (RuleCall)cAlternatives_1.eContents().get(0);
		private final RuleCall cAudioClipParserRuleCall_1_1 = (RuleCall)cAlternatives_1.eContents().get(1);
		
		//AudioElement:
		//	'audioElement' (Audio | AudioClip);
		@Override public ParserRule getRule() { return rule; }
		
		//'audioElement' (Audio | AudioClip)
		public Group getGroup() { return cGroup; }
		
		//'audioElement'
		public Keyword getAudioElementKeyword_0() { return cAudioElementKeyword_0; }
		
		//(Audio | AudioClip)
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//Audio
		public RuleCall getAudioParserRuleCall_1_0() { return cAudioParserRuleCall_1_0; }
		
		//AudioClip
		public RuleCall getAudioClipParserRuleCall_1_1() { return cAudioClipParserRuleCall_1_1; }
	}
	public class VideoElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.svjd.VideoMontage.VideoElement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVideoElementKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final RuleCall cTitleParserRuleCall_1_0 = (RuleCall)cAlternatives_1.eContents().get(0);
		private final RuleCall cClipParserRuleCall_1_1 = (RuleCall)cAlternatives_1.eContents().get(1);
		private final RuleCall cVideoParserRuleCall_1_2 = (RuleCall)cAlternatives_1.eContents().get(2);
		
		//VideoElement:
		//	'videoElement' (Title | Clip | Video);
		@Override public ParserRule getRule() { return rule; }
		
		//'videoElement' (Title | Clip | Video)
		public Group getGroup() { return cGroup; }
		
		//'videoElement'
		public Keyword getVideoElementKeyword_0() { return cVideoElementKeyword_0; }
		
		//(Title | Clip | Video)
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//Title
		public RuleCall getTitleParserRuleCall_1_0() { return cTitleParserRuleCall_1_0; }
		
		//Clip
		public RuleCall getClipParserRuleCall_1_1() { return cClipParserRuleCall_1_1; }
		
		//Video
		public RuleCall getVideoParserRuleCall_1_2() { return cVideoParserRuleCall_1_2; }
	}
	public class TextAreaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.svjd.VideoMontage.TextArea");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cTextArea_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cTextAreaDynamicParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//TextArea:
		//	TextArea_Impl | TextAreaDynamic;
		@Override public ParserRule getRule() { return rule; }
		
		//TextArea_Impl | TextAreaDynamic
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//TextArea_Impl
		public RuleCall getTextArea_ImplParserRuleCall_0() { return cTextArea_ImplParserRuleCall_0; }
		
		//TextAreaDynamic
		public RuleCall getTextAreaDynamicParserRuleCall_1() { return cTextAreaDynamicParserRuleCall_1; }
	}
	public class StartingMomentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.svjd.VideoMontage.StartingMoment");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cStartingMoment_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cRelativeMomentParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cAbsoluteMomentParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//StartingMoment:
		//	StartingMoment_Impl | RelativeMoment | AbsoluteMoment;
		@Override public ParserRule getRule() { return rule; }
		
		//StartingMoment_Impl | RelativeMoment | AbsoluteMoment
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//StartingMoment_Impl
		public RuleCall getStartingMoment_ImplParserRuleCall_0() { return cStartingMoment_ImplParserRuleCall_0; }
		
		//RelativeMoment
		public RuleCall getRelativeMomentParserRuleCall_1() { return cRelativeMomentParserRuleCall_1; }
		
		//AbsoluteMoment
		public RuleCall getAbsoluteMomentParserRuleCall_2() { return cAbsoluteMomentParserRuleCall_2; }
	}
	public class AnimationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.svjd.VideoMontage.Animation");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cFadeInParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cFadeOutParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Animation:
		//	FadeIn | FadeOut;
		@Override public ParserRule getRule() { return rule; }
		
		//FadeIn | FadeOut
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//FadeIn
		public RuleCall getFadeInParserRuleCall_0() { return cFadeInParserRuleCall_0; }
		
		//FadeOut
		public RuleCall getFadeOutParserRuleCall_1() { return cFadeOutParserRuleCall_1; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.svjd.VideoMontage.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class SubtitleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.svjd.VideoMontage.Subtitle");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSubtitleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cStartKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cStartingmomentAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cStartingmomentStartingMomentParserRuleCall_4_0 = (RuleCall)cStartingmomentAssignment_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cDurationKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cDurationAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cDurationEDoubleParserRuleCall_6_1_0 = (RuleCall)cDurationAssignment_6_1.eContents().get(0);
		private final Keyword cTextAreaKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cTextareaAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cTextareaTextAreaParserRuleCall_8_0 = (RuleCall)cTextareaAssignment_8.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Subtitle:
		//	'Subtitle'
		//	name=EString 'start' ':' startingmoment=StartingMoment
		//	'{' ('duration' duration=EDouble)?
		//	'textArea' textarea=TextArea
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Subtitle' name=EString 'start' ':' startingmoment=StartingMoment '{' ('duration' duration=EDouble)? 'textArea'
		//textarea=TextArea '}'
		public Group getGroup() { return cGroup; }
		
		//'Subtitle'
		public Keyword getSubtitleKeyword_0() { return cSubtitleKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'start'
		public Keyword getStartKeyword_2() { return cStartKeyword_2; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//startingmoment=StartingMoment
		public Assignment getStartingmomentAssignment_4() { return cStartingmomentAssignment_4; }
		
		//StartingMoment
		public RuleCall getStartingmomentStartingMomentParserRuleCall_4_0() { return cStartingmomentStartingMomentParserRuleCall_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//('duration' duration=EDouble)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'duration'
		public Keyword getDurationKeyword_6_0() { return cDurationKeyword_6_0; }
		
		//duration=EDouble
		public Assignment getDurationAssignment_6_1() { return cDurationAssignment_6_1; }
		
		//EDouble
		public RuleCall getDurationEDoubleParserRuleCall_6_1_0() { return cDurationEDoubleParserRuleCall_6_1_0; }
		
		//'textArea'
		public Keyword getTextAreaKeyword_7() { return cTextAreaKeyword_7; }
		
		//textarea=TextArea
		public Assignment getTextareaAssignment_8() { return cTextareaAssignment_8; }
		
		//TextArea
		public RuleCall getTextareaTextAreaParserRuleCall_8_0() { return cTextareaTextAreaParserRuleCall_8_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class AudioElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.svjd.VideoMontage.Audio");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAudioKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cStartKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cStartingmomentAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cStartingmomentStartingMomentParserRuleCall_4_0 = (RuleCall)cStartingmomentAssignment_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cPathKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cPathAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cPathEStringParserRuleCall_6_1_0 = (RuleCall)cPathAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cTransitionKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cTransitionAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cTransitionTransitionParserRuleCall_7_1_0 = (RuleCall)cTransitionAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Audio:
		//	'Audio'
		//	name=EString 'start' ':' startingmoment=StartingMoment
		//	'{' ('path' path=EString)? ('transition' transition=Transition)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Audio' name=EString 'start' ':' startingmoment=StartingMoment '{' ('path' path=EString)? ('transition'
		//transition=Transition)? '}'
		public Group getGroup() { return cGroup; }
		
		//'Audio'
		public Keyword getAudioKeyword_0() { return cAudioKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'start'
		public Keyword getStartKeyword_2() { return cStartKeyword_2; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//startingmoment=StartingMoment
		public Assignment getStartingmomentAssignment_4() { return cStartingmomentAssignment_4; }
		
		//StartingMoment
		public RuleCall getStartingmomentStartingMomentParserRuleCall_4_0() { return cStartingmomentStartingMomentParserRuleCall_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//('path' path=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'path'
		public Keyword getPathKeyword_6_0() { return cPathKeyword_6_0; }
		
		//path=EString
		public Assignment getPathAssignment_6_1() { return cPathAssignment_6_1; }
		
		//EString
		public RuleCall getPathEStringParserRuleCall_6_1_0() { return cPathEStringParserRuleCall_6_1_0; }
		
		//('transition' transition=Transition)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'transition'
		public Keyword getTransitionKeyword_7_0() { return cTransitionKeyword_7_0; }
		
		//transition=Transition
		public Assignment getTransitionAssignment_7_1() { return cTransitionAssignment_7_1; }
		
		//Transition
		public RuleCall getTransitionTransitionParserRuleCall_7_1_0() { return cTransitionTransitionParserRuleCall_7_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class AudioClipElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.svjd.VideoMontage.AudioClip");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAudioClipKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cStartKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cStartingmomentAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cStartingmomentStartingMomentParserRuleCall_4_0 = (RuleCall)cStartingmomentAssignment_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cVolumeKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cVolumeAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cVolumeEDoubleParserRuleCall_6_1_0 = (RuleCall)cVolumeAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cStartCutKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cStartCutAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cStartCutEDoubleParserRuleCall_7_1_0 = (RuleCall)cStartCutAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cEndCutKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cEndCutAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cEndCutEDoubleParserRuleCall_8_1_0 = (RuleCall)cEndCutAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cTransitionKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cTransitionAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cTransitionTransitionParserRuleCall_9_1_0 = (RuleCall)cTransitionAssignment_9_1.eContents().get(0);
		private final Keyword cAudioKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cAudioAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final CrossReference cAudioAudioCrossReference_11_0 = (CrossReference)cAudioAssignment_11.eContents().get(0);
		private final RuleCall cAudioAudioIDTerminalRuleCall_11_0_1 = (RuleCall)cAudioAudioCrossReference_11_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//AudioClip:
		//	'AudioClip'
		//	name=EString 'start' ':' startingmoment=StartingMoment
		//	'{' ('volume' volume=EDouble)? ('startCut' startCut=EDouble) ('endCut' endCut=EDouble) ('transition'
		//	transition=Transition)?
		//	'audio' audio+=[Audio]*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'AudioClip' name=EString 'start' ':' startingmoment=StartingMoment '{' ('volume' volume=EDouble)? ('startCut'
		//startCut=EDouble) ('endCut' endCut=EDouble) ('transition' transition=Transition)? 'audio' audio+=[Audio]* '}'
		public Group getGroup() { return cGroup; }
		
		//'AudioClip'
		public Keyword getAudioClipKeyword_0() { return cAudioClipKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'start'
		public Keyword getStartKeyword_2() { return cStartKeyword_2; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//startingmoment=StartingMoment
		public Assignment getStartingmomentAssignment_4() { return cStartingmomentAssignment_4; }
		
		//StartingMoment
		public RuleCall getStartingmomentStartingMomentParserRuleCall_4_0() { return cStartingmomentStartingMomentParserRuleCall_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//('volume' volume=EDouble)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'volume'
		public Keyword getVolumeKeyword_6_0() { return cVolumeKeyword_6_0; }
		
		//volume=EDouble
		public Assignment getVolumeAssignment_6_1() { return cVolumeAssignment_6_1; }
		
		//EDouble
		public RuleCall getVolumeEDoubleParserRuleCall_6_1_0() { return cVolumeEDoubleParserRuleCall_6_1_0; }
		
		//('startCut' startCut=EDouble)
		public Group getGroup_7() { return cGroup_7; }
		
		//'startCut'
		public Keyword getStartCutKeyword_7_0() { return cStartCutKeyword_7_0; }
		
		//startCut=EDouble
		public Assignment getStartCutAssignment_7_1() { return cStartCutAssignment_7_1; }
		
		//EDouble
		public RuleCall getStartCutEDoubleParserRuleCall_7_1_0() { return cStartCutEDoubleParserRuleCall_7_1_0; }
		
		//('endCut' endCut=EDouble)
		public Group getGroup_8() { return cGroup_8; }
		
		//'endCut'
		public Keyword getEndCutKeyword_8_0() { return cEndCutKeyword_8_0; }
		
		//endCut=EDouble
		public Assignment getEndCutAssignment_8_1() { return cEndCutAssignment_8_1; }
		
		//EDouble
		public RuleCall getEndCutEDoubleParserRuleCall_8_1_0() { return cEndCutEDoubleParserRuleCall_8_1_0; }
		
		//('transition' transition=Transition)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'transition'
		public Keyword getTransitionKeyword_9_0() { return cTransitionKeyword_9_0; }
		
		//transition=Transition
		public Assignment getTransitionAssignment_9_1() { return cTransitionAssignment_9_1; }
		
		//Transition
		public RuleCall getTransitionTransitionParserRuleCall_9_1_0() { return cTransitionTransitionParserRuleCall_9_1_0; }
		
		//'audio'
		public Keyword getAudioKeyword_10() { return cAudioKeyword_10; }
		
		//audio+=[Audio]*
		public Assignment getAudioAssignment_11() { return cAudioAssignment_11; }
		
		//[Audio]
		public CrossReference getAudioAudioCrossReference_11_0() { return cAudioAudioCrossReference_11_0; }
		
		//ID
		public RuleCall getAudioAudioIDTerminalRuleCall_11_0_1() { return cAudioAudioIDTerminalRuleCall_11_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	public class ClipElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.svjd.VideoMontage.Clip");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cClipKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cStartCutKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cStartCutAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cStartCutEDoubleParserRuleCall_3_1_0 = (RuleCall)cStartCutAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cEndCutKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cEndCutAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cEndCutEDoubleParserRuleCall_4_1_0 = (RuleCall)cEndCutAssignment_4_1.eContents().get(0);
		private final Keyword cVideoKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cVideoAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cVideoVideoCrossReference_6_0 = (CrossReference)cVideoAssignment_6.eContents().get(0);
		private final RuleCall cVideoVideoIDTerminalRuleCall_6_0_1 = (RuleCall)cVideoVideoCrossReference_6_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Clip:
		//	'Clip'
		//	name=EString
		//	'{' ('startCut' startCut=EDouble)? ('endCut' endCut=EDouble)?
		//	'video' video+=[Video]*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Clip' name=EString '{' ('startCut' startCut=EDouble)? ('endCut' endCut=EDouble)? 'video' video+=[Video]* '}'
		public Group getGroup() { return cGroup; }
		
		//'Clip'
		public Keyword getClipKeyword_0() { return cClipKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('startCut' startCut=EDouble)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'startCut'
		public Keyword getStartCutKeyword_3_0() { return cStartCutKeyword_3_0; }
		
		//startCut=EDouble
		public Assignment getStartCutAssignment_3_1() { return cStartCutAssignment_3_1; }
		
		//EDouble
		public RuleCall getStartCutEDoubleParserRuleCall_3_1_0() { return cStartCutEDoubleParserRuleCall_3_1_0; }
		
		//('endCut' endCut=EDouble)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'endCut'
		public Keyword getEndCutKeyword_4_0() { return cEndCutKeyword_4_0; }
		
		//endCut=EDouble
		public Assignment getEndCutAssignment_4_1() { return cEndCutAssignment_4_1; }
		
		//EDouble
		public RuleCall getEndCutEDoubleParserRuleCall_4_1_0() { return cEndCutEDoubleParserRuleCall_4_1_0; }
		
		//'video'
		public Keyword getVideoKeyword_5() { return cVideoKeyword_5; }
		
		//video+=[Video]*
		public Assignment getVideoAssignment_6() { return cVideoAssignment_6; }
		
		//[Video]
		public CrossReference getVideoVideoCrossReference_6_0() { return cVideoVideoCrossReference_6_0; }
		
		//ID
		public RuleCall getVideoVideoIDTerminalRuleCall_6_0_1() { return cVideoVideoIDTerminalRuleCall_6_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class TitleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.svjd.VideoMontage.Title");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTitleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDurationKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDurationAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cDurationEDoubleParserRuleCall_3_1_0 = (RuleCall)cDurationAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cBackgroundColorKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cBackgroundColorAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cBackgroundColorColorEnumRuleCall_4_1_0 = (RuleCall)cBackgroundColorAssignment_4_1.eContents().get(0);
		private final Keyword cTextAreaKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cTextareaAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cTextareaTextAreaParserRuleCall_6_0 = (RuleCall)cTextareaAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Title:
		//	'Title'
		//	name=EString
		//	'{' ('duration' duration=EDouble)? ('backgroundColor' backgroundColor=Color)?
		//	'textArea' textarea=TextArea
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Title' name=EString '{' ('duration' duration=EDouble)? ('backgroundColor' backgroundColor=Color)? 'textArea'
		//textarea=TextArea '}'
		public Group getGroup() { return cGroup; }
		
		//'Title'
		public Keyword getTitleKeyword_0() { return cTitleKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('duration' duration=EDouble)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'duration'
		public Keyword getDurationKeyword_3_0() { return cDurationKeyword_3_0; }
		
		//duration=EDouble
		public Assignment getDurationAssignment_3_1() { return cDurationAssignment_3_1; }
		
		//EDouble
		public RuleCall getDurationEDoubleParserRuleCall_3_1_0() { return cDurationEDoubleParserRuleCall_3_1_0; }
		
		//('backgroundColor' backgroundColor=Color)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'backgroundColor'
		public Keyword getBackgroundColorKeyword_4_0() { return cBackgroundColorKeyword_4_0; }
		
		//backgroundColor=Color
		public Assignment getBackgroundColorAssignment_4_1() { return cBackgroundColorAssignment_4_1; }
		
		//Color
		public RuleCall getBackgroundColorColorEnumRuleCall_4_1_0() { return cBackgroundColorColorEnumRuleCall_4_1_0; }
		
		//'textArea'
		public Keyword getTextAreaKeyword_5() { return cTextAreaKeyword_5; }
		
		//textarea=TextArea
		public Assignment getTextareaAssignment_6() { return cTextareaAssignment_6; }
		
		//TextArea
		public RuleCall getTextareaTextAreaParserRuleCall_6_0() { return cTextareaTextAreaParserRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class VideoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.svjd.VideoMontage.Video");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameEStringParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cPathKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cPathAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cPathEStringParserRuleCall_1_1_0 = (RuleCall)cPathAssignment_1_1.eContents().get(0);
		
		//Video:
		//	name=EString ('path' path=EString);
		@Override public ParserRule getRule() { return rule; }
		
		//name=EString ('path' path=EString)
		public Group getGroup() { return cGroup; }
		
		//name=EString
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_0_0() { return cNameEStringParserRuleCall_0_0; }
		
		//('path' path=EString)
		public Group getGroup_1() { return cGroup_1; }
		
		//'path'
		public Keyword getPathKeyword_1_0() { return cPathKeyword_1_0; }
		
		//path=EString
		public Assignment getPathAssignment_1_1() { return cPathAssignment_1_1; }
		
		//EString
		public RuleCall getPathEStringParserRuleCall_1_1_0() { return cPathEStringParserRuleCall_1_1_0; }
	}
	public class RelativeMomentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.svjd.VideoMontage.RelativeMoment");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRelativeMomentAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cMomentAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cMomentMomentEnumRuleCall_1_0 = (RuleCall)cMomentAssignment_1.eContents().get(0);
		private final Keyword cOfKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cElementAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cElementElementCrossReference_3_0 = (CrossReference)cElementAssignment_3.eContents().get(0);
		private final RuleCall cElementElementIDTerminalRuleCall_3_0_1 = (RuleCall)cElementElementCrossReference_3_0.eContents().get(1);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Assignment cOperationMomentAssignment_4_0 = (Assignment)cGroup_4.eContents().get(0);
		private final RuleCall cOperationMomentOperationMomentEnumRuleCall_4_0_0 = (RuleCall)cOperationMomentAssignment_4_0.eContents().get(0);
		private final Assignment cValueAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cValueEDoubleParserRuleCall_4_1_0 = (RuleCall)cValueAssignment_4_1.eContents().get(0);
		
		//RelativeMoment:
		//	{RelativeMoment} moment=Moment? 'of' element=[Element] (operationMoment=OperationMoment value=EDouble)?;
		@Override public ParserRule getRule() { return rule; }
		
		//{RelativeMoment} moment=Moment? 'of' element=[Element] (operationMoment=OperationMoment value=EDouble)?
		public Group getGroup() { return cGroup; }
		
		//{RelativeMoment}
		public Action getRelativeMomentAction_0() { return cRelativeMomentAction_0; }
		
		//moment=Moment?
		public Assignment getMomentAssignment_1() { return cMomentAssignment_1; }
		
		//Moment
		public RuleCall getMomentMomentEnumRuleCall_1_0() { return cMomentMomentEnumRuleCall_1_0; }
		
		//'of'
		public Keyword getOfKeyword_2() { return cOfKeyword_2; }
		
		//element=[Element]
		public Assignment getElementAssignment_3() { return cElementAssignment_3; }
		
		//[Element]
		public CrossReference getElementElementCrossReference_3_0() { return cElementElementCrossReference_3_0; }
		
		//ID
		public RuleCall getElementElementIDTerminalRuleCall_3_0_1() { return cElementElementIDTerminalRuleCall_3_0_1; }
		
		//(operationMoment=OperationMoment value=EDouble)?
		public Group getGroup_4() { return cGroup_4; }
		
		//operationMoment=OperationMoment
		public Assignment getOperationMomentAssignment_4_0() { return cOperationMomentAssignment_4_0; }
		
		//OperationMoment
		public RuleCall getOperationMomentOperationMomentEnumRuleCall_4_0_0() { return cOperationMomentOperationMomentEnumRuleCall_4_0_0; }
		
		//value=EDouble
		public Assignment getValueAssignment_4_1() { return cValueAssignment_4_1; }
		
		//EDouble
		public RuleCall getValueEDoubleParserRuleCall_4_1_0() { return cValueEDoubleParserRuleCall_4_1_0; }
	}
	public class AbsoluteMomentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.svjd.VideoMontage.AbsoluteMoment");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAbsoluteMomentAction_0 = (Action)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cTimeKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cTimeAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cTimeEDoubleParserRuleCall_1_1_0 = (RuleCall)cTimeAssignment_1_1.eContents().get(0);
		
		//AbsoluteMoment:
		//	{AbsoluteMoment} ('time' time=EDouble)?;
		@Override public ParserRule getRule() { return rule; }
		
		//{AbsoluteMoment} ('time' time=EDouble)?
		public Group getGroup() { return cGroup; }
		
		//{AbsoluteMoment}
		public Action getAbsoluteMomentAction_0() { return cAbsoluteMomentAction_0; }
		
		//('time' time=EDouble)?
		public Group getGroup_1() { return cGroup_1; }
		
		//'time'
		public Keyword getTimeKeyword_1_0() { return cTimeKeyword_1_0; }
		
		//time=EDouble
		public Assignment getTimeAssignment_1_1() { return cTimeAssignment_1_1; }
		
		//EDouble
		public RuleCall getTimeEDoubleParserRuleCall_1_1_0() { return cTimeEDoubleParserRuleCall_1_1_0; }
	}
	public class StartingMoment_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.svjd.VideoMontage.StartingMoment_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStartingMomentAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cStartingMomentKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//StartingMoment_Impl StartingMoment:
		//	{StartingMoment}
		//	'StartingMoment';
		@Override public ParserRule getRule() { return rule; }
		
		//{StartingMoment} 'StartingMoment'
		public Group getGroup() { return cGroup; }
		
		//{StartingMoment}
		public Action getStartingMomentAction_0() { return cStartingMomentAction_0; }
		
		//'StartingMoment'
		public Keyword getStartingMomentKeyword_1() { return cStartingMomentKeyword_1; }
	}
	public class TransitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.svjd.VideoMontage.Transition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTransitionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cDurationKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cDurationAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cDurationEDoubleParserRuleCall_2_1_0 = (RuleCall)cDurationAssignment_2_1.eContents().get(0);
		private final Keyword cAudioElementKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cAudioelementAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cAudioelementAudioElementParserRuleCall_4_0 = (RuleCall)cAudioelementAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Transition:
		//	'Transition'
		//	'{' ('duration' duration=EDouble)?
		//	'audioElement' audioelement=AudioElement
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Transition' '{' ('duration' duration=EDouble)? 'audioElement' audioelement=AudioElement '}'
		public Group getGroup() { return cGroup; }
		
		//'Transition'
		public Keyword getTransitionKeyword_0() { return cTransitionKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('duration' duration=EDouble)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'duration'
		public Keyword getDurationKeyword_2_0() { return cDurationKeyword_2_0; }
		
		//duration=EDouble
		public Assignment getDurationAssignment_2_1() { return cDurationAssignment_2_1; }
		
		//EDouble
		public RuleCall getDurationEDoubleParserRuleCall_2_1_0() { return cDurationEDoubleParserRuleCall_2_1_0; }
		
		//'audioElement'
		public Keyword getAudioElementKeyword_3() { return cAudioElementKeyword_3; }
		
		//audioelement=AudioElement
		public Assignment getAudioelementAssignment_4() { return cAudioelementAssignment_4; }
		
		//AudioElement
		public RuleCall getAudioelementAudioElementParserRuleCall_4_0() { return cAudioelementAudioElementParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class TextArea_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.svjd.VideoMontage.TextArea_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTextAreaKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cXKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cXAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cXEIntParserRuleCall_2_1_0 = (RuleCall)cXAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cYKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cYAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cYEIntParserRuleCall_3_1_0 = (RuleCall)cYAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cWidthKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cWidthAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cWidthEDoubleParserRuleCall_4_1_0 = (RuleCall)cWidthAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cHeightKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cHeightAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cHeightEDoubleParserRuleCall_5_1_0 = (RuleCall)cHeightAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cTextKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cTextAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cTextEStringParserRuleCall_6_1_0 = (RuleCall)cTextAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cFontKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cFontAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final CrossReference cFontFontCrossReference_7_1_0 = (CrossReference)cFontAssignment_7_1.eContents().get(0);
		private final RuleCall cFontFontIDTerminalRuleCall_7_1_0_1 = (RuleCall)cFontFontCrossReference_7_1_0.eContents().get(1);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cAnimationKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cAnimationAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cAnimationAnimationParserRuleCall_8_1_0 = (RuleCall)cAnimationAssignment_8_1.eContents().get(0);
		private final Assignment cAnimationAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cAnimationAnimationParserRuleCall_8_2_0 = (RuleCall)cAnimationAssignment_8_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//TextArea_Impl TextArea:
		//	'TextArea'
		//	'{' ('x' x=EInt)? ('y' y=EInt)? ('width' width=EDouble)? ('height' height=EDouble)? ('text' text=EString) ('font'
		//	font=[Font])? ('animation' animation+=Animation animation+=Animation*)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'TextArea' '{' ('x' x=EInt)? ('y' y=EInt)? ('width' width=EDouble)? ('height' height=EDouble)? ('text' text=EString)
		//('font' font=[Font])? ('animation' animation+=Animation animation+=Animation*)? '}'
		public Group getGroup() { return cGroup; }
		
		//'TextArea'
		public Keyword getTextAreaKeyword_0() { return cTextAreaKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('x' x=EInt)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'x'
		public Keyword getXKeyword_2_0() { return cXKeyword_2_0; }
		
		//x=EInt
		public Assignment getXAssignment_2_1() { return cXAssignment_2_1; }
		
		//EInt
		public RuleCall getXEIntParserRuleCall_2_1_0() { return cXEIntParserRuleCall_2_1_0; }
		
		//('y' y=EInt)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'y'
		public Keyword getYKeyword_3_0() { return cYKeyword_3_0; }
		
		//y=EInt
		public Assignment getYAssignment_3_1() { return cYAssignment_3_1; }
		
		//EInt
		public RuleCall getYEIntParserRuleCall_3_1_0() { return cYEIntParserRuleCall_3_1_0; }
		
		//('width' width=EDouble)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'width'
		public Keyword getWidthKeyword_4_0() { return cWidthKeyword_4_0; }
		
		//width=EDouble
		public Assignment getWidthAssignment_4_1() { return cWidthAssignment_4_1; }
		
		//EDouble
		public RuleCall getWidthEDoubleParserRuleCall_4_1_0() { return cWidthEDoubleParserRuleCall_4_1_0; }
		
		//('height' height=EDouble)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'height'
		public Keyword getHeightKeyword_5_0() { return cHeightKeyword_5_0; }
		
		//height=EDouble
		public Assignment getHeightAssignment_5_1() { return cHeightAssignment_5_1; }
		
		//EDouble
		public RuleCall getHeightEDoubleParserRuleCall_5_1_0() { return cHeightEDoubleParserRuleCall_5_1_0; }
		
		//('text' text=EString)
		public Group getGroup_6() { return cGroup_6; }
		
		//'text'
		public Keyword getTextKeyword_6_0() { return cTextKeyword_6_0; }
		
		//text=EString
		public Assignment getTextAssignment_6_1() { return cTextAssignment_6_1; }
		
		//EString
		public RuleCall getTextEStringParserRuleCall_6_1_0() { return cTextEStringParserRuleCall_6_1_0; }
		
		//('font' font=[Font])?
		public Group getGroup_7() { return cGroup_7; }
		
		//'font'
		public Keyword getFontKeyword_7_0() { return cFontKeyword_7_0; }
		
		//font=[Font]
		public Assignment getFontAssignment_7_1() { return cFontAssignment_7_1; }
		
		//[Font]
		public CrossReference getFontFontCrossReference_7_1_0() { return cFontFontCrossReference_7_1_0; }
		
		//ID
		public RuleCall getFontFontIDTerminalRuleCall_7_1_0_1() { return cFontFontIDTerminalRuleCall_7_1_0_1; }
		
		//('animation' animation+=Animation animation+=Animation*)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'animation'
		public Keyword getAnimationKeyword_8_0() { return cAnimationKeyword_8_0; }
		
		//animation+=Animation
		public Assignment getAnimationAssignment_8_1() { return cAnimationAssignment_8_1; }
		
		//Animation
		public RuleCall getAnimationAnimationParserRuleCall_8_1_0() { return cAnimationAnimationParserRuleCall_8_1_0; }
		
		//animation+=Animation*
		public Assignment getAnimationAssignment_8_2() { return cAnimationAssignment_8_2; }
		
		//Animation
		public RuleCall getAnimationAnimationParserRuleCall_8_2_0() { return cAnimationAnimationParserRuleCall_8_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class FontElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.svjd.VideoMontage.Font");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFontAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cFontStyleAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cFontStyleFontStyleEnumRuleCall_1_0 = (RuleCall)cFontStyleAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLengthKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cLengthAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cLengthEStringParserRuleCall_2_1_0 = (RuleCall)cLengthAssignment_2_1.eContents().get(0);
		
		//Font:
		//	{Font} fontStyle=FontStyle ('length' length=EString);
		@Override public ParserRule getRule() { return rule; }
		
		//{Font} fontStyle=FontStyle ('length' length=EString)
		public Group getGroup() { return cGroup; }
		
		//{Font}
		public Action getFontAction_0() { return cFontAction_0; }
		
		//fontStyle=FontStyle
		public Assignment getFontStyleAssignment_1() { return cFontStyleAssignment_1; }
		
		//FontStyle
		public RuleCall getFontStyleFontStyleEnumRuleCall_1_0() { return cFontStyleFontStyleEnumRuleCall_1_0; }
		
		//('length' length=EString)
		public Group getGroup_2() { return cGroup_2; }
		
		//'length'
		public Keyword getLengthKeyword_2_0() { return cLengthKeyword_2_0; }
		
		//length=EString
		public Assignment getLengthAssignment_2_1() { return cLengthAssignment_2_1; }
		
		//EString
		public RuleCall getLengthEStringParserRuleCall_2_1_0() { return cLengthEStringParserRuleCall_2_1_0; }
	}
	public class TextAreaDynamicElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.svjd.VideoMontage.TextAreaDynamic");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTextAreaDynamicKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cXKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cXAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cXEIntParserRuleCall_2_1_0 = (RuleCall)cXAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cYKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cYAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cYEIntParserRuleCall_3_1_0 = (RuleCall)cYAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cWidthKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cWidthAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cWidthEDoubleParserRuleCall_4_1_0 = (RuleCall)cWidthAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cHeightKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cHeightAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cHeightEDoubleParserRuleCall_5_1_0 = (RuleCall)cHeightAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cTextKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cTextAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cTextEStringParserRuleCall_6_1_0 = (RuleCall)cTextAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cTextSrcKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cTextSrcAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cTextSrcEStringParserRuleCall_7_1_0 = (RuleCall)cTextSrcAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cLineKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cLineAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cLineEIntParserRuleCall_8_1_0 = (RuleCall)cLineAssignment_8_1.eContents().get(0);
		private final Keyword cFontKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cFontAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final CrossReference cFontFontCrossReference_10_0 = (CrossReference)cFontAssignment_10.eContents().get(0);
		private final RuleCall cFontFontEStringParserRuleCall_10_0_1 = (RuleCall)cFontFontCrossReference_10_0.eContents().get(1);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cAnimationKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cAnimationAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall cAnimationAnimationParserRuleCall_11_1_0 = (RuleCall)cAnimationAssignment_11_1.eContents().get(0);
		private final Assignment cAnimationAssignment_11_2 = (Assignment)cGroup_11.eContents().get(2);
		private final RuleCall cAnimationAnimationParserRuleCall_11_2_0 = (RuleCall)cAnimationAssignment_11_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//TextAreaDynamic:
		//	'TextAreaDynamic'
		//	'{' ('x' x=EInt)? ('y' y=EInt)? ('width' width=EDouble)? ('height' height=EDouble)? ('text' text=EString)? ('textSrc'
		//	textSrc=EString)? ('line' line=EInt)?
		//	'font' font=[Font|EString] ('animation' animation+=Animation animation+=Animation*)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'TextAreaDynamic' '{' ('x' x=EInt)? ('y' y=EInt)? ('width' width=EDouble)? ('height' height=EDouble)? ('text'
		//text=EString)? ('textSrc' textSrc=EString)? ('line' line=EInt)? 'font' font=[Font|EString] ('animation'
		//animation+=Animation animation+=Animation*)? '}'
		public Group getGroup() { return cGroup; }
		
		//'TextAreaDynamic'
		public Keyword getTextAreaDynamicKeyword_0() { return cTextAreaDynamicKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('x' x=EInt)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'x'
		public Keyword getXKeyword_2_0() { return cXKeyword_2_0; }
		
		//x=EInt
		public Assignment getXAssignment_2_1() { return cXAssignment_2_1; }
		
		//EInt
		public RuleCall getXEIntParserRuleCall_2_1_0() { return cXEIntParserRuleCall_2_1_0; }
		
		//('y' y=EInt)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'y'
		public Keyword getYKeyword_3_0() { return cYKeyword_3_0; }
		
		//y=EInt
		public Assignment getYAssignment_3_1() { return cYAssignment_3_1; }
		
		//EInt
		public RuleCall getYEIntParserRuleCall_3_1_0() { return cYEIntParserRuleCall_3_1_0; }
		
		//('width' width=EDouble)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'width'
		public Keyword getWidthKeyword_4_0() { return cWidthKeyword_4_0; }
		
		//width=EDouble
		public Assignment getWidthAssignment_4_1() { return cWidthAssignment_4_1; }
		
		//EDouble
		public RuleCall getWidthEDoubleParserRuleCall_4_1_0() { return cWidthEDoubleParserRuleCall_4_1_0; }
		
		//('height' height=EDouble)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'height'
		public Keyword getHeightKeyword_5_0() { return cHeightKeyword_5_0; }
		
		//height=EDouble
		public Assignment getHeightAssignment_5_1() { return cHeightAssignment_5_1; }
		
		//EDouble
		public RuleCall getHeightEDoubleParserRuleCall_5_1_0() { return cHeightEDoubleParserRuleCall_5_1_0; }
		
		//('text' text=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'text'
		public Keyword getTextKeyword_6_0() { return cTextKeyword_6_0; }
		
		//text=EString
		public Assignment getTextAssignment_6_1() { return cTextAssignment_6_1; }
		
		//EString
		public RuleCall getTextEStringParserRuleCall_6_1_0() { return cTextEStringParserRuleCall_6_1_0; }
		
		//('textSrc' textSrc=EString)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'textSrc'
		public Keyword getTextSrcKeyword_7_0() { return cTextSrcKeyword_7_0; }
		
		//textSrc=EString
		public Assignment getTextSrcAssignment_7_1() { return cTextSrcAssignment_7_1; }
		
		//EString
		public RuleCall getTextSrcEStringParserRuleCall_7_1_0() { return cTextSrcEStringParserRuleCall_7_1_0; }
		
		//('line' line=EInt)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'line'
		public Keyword getLineKeyword_8_0() { return cLineKeyword_8_0; }
		
		//line=EInt
		public Assignment getLineAssignment_8_1() { return cLineAssignment_8_1; }
		
		//EInt
		public RuleCall getLineEIntParserRuleCall_8_1_0() { return cLineEIntParserRuleCall_8_1_0; }
		
		//'font'
		public Keyword getFontKeyword_9() { return cFontKeyword_9; }
		
		//font=[Font|EString]
		public Assignment getFontAssignment_10() { return cFontAssignment_10; }
		
		//[Font|EString]
		public CrossReference getFontFontCrossReference_10_0() { return cFontFontCrossReference_10_0; }
		
		//EString
		public RuleCall getFontFontEStringParserRuleCall_10_0_1() { return cFontFontEStringParserRuleCall_10_0_1; }
		
		//('animation' animation+=Animation animation+=Animation*)?
		public Group getGroup_11() { return cGroup_11; }
		
		//'animation'
		public Keyword getAnimationKeyword_11_0() { return cAnimationKeyword_11_0; }
		
		//animation+=Animation
		public Assignment getAnimationAssignment_11_1() { return cAnimationAssignment_11_1; }
		
		//Animation
		public RuleCall getAnimationAnimationParserRuleCall_11_1_0() { return cAnimationAnimationParserRuleCall_11_1_0; }
		
		//animation+=Animation*
		public Assignment getAnimationAssignment_11_2() { return cAnimationAssignment_11_2; }
		
		//Animation
		public RuleCall getAnimationAnimationParserRuleCall_11_2_0() { return cAnimationAnimationParserRuleCall_11_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	public class FadeInElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.svjd.VideoMontage.FadeIn");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFadeInAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFadeInKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDurationKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDurationAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cDurationEDoubleParserRuleCall_3_1_0 = (RuleCall)cDurationAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//FadeIn:
		//	{FadeIn}
		//	'FadeIn'
		//	'{' ('duration' duration=EDouble)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{FadeIn} 'FadeIn' '{' ('duration' duration=EDouble)? '}'
		public Group getGroup() { return cGroup; }
		
		//{FadeIn}
		public Action getFadeInAction_0() { return cFadeInAction_0; }
		
		//'FadeIn'
		public Keyword getFadeInKeyword_1() { return cFadeInKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('duration' duration=EDouble)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'duration'
		public Keyword getDurationKeyword_3_0() { return cDurationKeyword_3_0; }
		
		//duration=EDouble
		public Assignment getDurationAssignment_3_1() { return cDurationAssignment_3_1; }
		
		//EDouble
		public RuleCall getDurationEDoubleParserRuleCall_3_1_0() { return cDurationEDoubleParserRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class FadeOutElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.svjd.VideoMontage.FadeOut");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFadeOutAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFadeOutKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDurationKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDurationAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cDurationEDoubleParserRuleCall_3_1_0 = (RuleCall)cDurationAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//FadeOut:
		//	{FadeOut}
		//	'FadeOut'
		//	'{' ('duration' duration=EDouble)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{FadeOut} 'FadeOut' '{' ('duration' duration=EDouble)? '}'
		public Group getGroup() { return cGroup; }
		
		//{FadeOut}
		public Action getFadeOutAction_0() { return cFadeOutAction_0; }
		
		//'FadeOut'
		public Keyword getFadeOutKeyword_1() { return cFadeOutKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('duration' duration=EDouble)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'duration'
		public Keyword getDurationKeyword_3_0() { return cDurationKeyword_3_0; }
		
		//duration=EDouble
		public Assignment getDurationAssignment_3_1() { return cDurationAssignment_3_1; }
		
		//EDouble
		public RuleCall getDurationEDoubleParserRuleCall_3_1_0() { return cDurationEDoubleParserRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class EDoubleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.svjd.VideoMontage.EDouble");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_4_0 = (Alternatives)cGroup_4.eContents().get(0);
		private final Keyword cEKeyword_4_0_0 = (Keyword)cAlternatives_4_0.eContents().get(0);
		private final Keyword cEKeyword_4_0_1 = (Keyword)cAlternatives_4_0.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		
		//EDouble ecore::EDouble:
		//	'-'? INT? '.' INT (('E' | 'e') '-'? INT)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT? '.' INT (('E' | 'e') '-'? INT)?
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT?
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }
		
		//(('E' | 'e') '-'? INT)?
		public Group getGroup_4() { return cGroup_4; }
		
		//('E' | 'e')
		public Alternatives getAlternatives_4_0() { return cAlternatives_4_0; }
		
		//'E'
		public Keyword getEKeyword_4_0_0() { return cEKeyword_4_0_0; }
		
		//'e'
		public Keyword getEKeyword_4_0_1() { return cEKeyword_4_0_1; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_4_1() { return cHyphenMinusKeyword_4_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_4_2() { return cINTTerminalRuleCall_4_2; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.svjd.VideoMontage.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt ecore::EInt:
		//	'-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	
	public class OperationMomentElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.svjd.VideoMontage.OperationMoment");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cAdditionEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cAdditionPlusSignKeyword_0_0 = (Keyword)cAdditionEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cSoustractionEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cSoustractionHyphenMinusKeyword_1_0 = (Keyword)cSoustractionEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum OperationMoment:
		//	Addition='+' |
		//	Soustraction="-";
		public EnumRule getRule() { return rule; }
		
		//Addition='+' | Soustraction="-"
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Addition='+'
		public EnumLiteralDeclaration getAdditionEnumLiteralDeclaration_0() { return cAdditionEnumLiteralDeclaration_0; }
		
		//'+'
		public Keyword getAdditionPlusSignKeyword_0_0() { return cAdditionPlusSignKeyword_0_0; }
		
		//Soustraction="-"
		public EnumLiteralDeclaration getSoustractionEnumLiteralDeclaration_1() { return cSoustractionEnumLiteralDeclaration_1; }
		
		//"-"
		public Keyword getSoustractionHyphenMinusKeyword_1_0() { return cSoustractionHyphenMinusKeyword_1_0; }
	}
	public class MomentElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.svjd.VideoMontage.Moment");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cStartingEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cStartingStartingKeyword_0_0 = (Keyword)cStartingEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cEndingEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cEndingEndingKeyword_1_0 = (Keyword)cEndingEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum Moment:
		//	starting | ending;
		public EnumRule getRule() { return rule; }
		
		//starting | ending
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//starting
		public EnumLiteralDeclaration getStartingEnumLiteralDeclaration_0() { return cStartingEnumLiteralDeclaration_0; }
		
		//'starting'
		public Keyword getStartingStartingKeyword_0_0() { return cStartingStartingKeyword_0_0; }
		
		//ending
		public EnumLiteralDeclaration getEndingEnumLiteralDeclaration_1() { return cEndingEnumLiteralDeclaration_1; }
		
		//'ending'
		public Keyword getEndingEndingKeyword_1_0() { return cEndingEndingKeyword_1_0; }
	}
	public class ColorElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.svjd.VideoMontage.Color");
		private final EnumLiteralDeclaration cBLACKEnumLiteralDeclaration = (EnumLiteralDeclaration)rule.eContents().get(1);
		private final Keyword cBLACKBLACKKeyword_0 = (Keyword)cBLACKEnumLiteralDeclaration.eContents().get(0);
		
		//enum Color:
		//	BLACK;
		public EnumRule getRule() { return rule; }
		
		//BLACK
		public EnumLiteralDeclaration getBLACKEnumLiteralDeclaration() { return cBLACKEnumLiteralDeclaration; }
		
		//'BLACK'
		public Keyword getBLACKBLACKKeyword_0() { return cBLACKBLACKKeyword_0; }
	}
	public class FontStyleElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.svjd.VideoMontage.FontStyle");
		private final EnumLiteralDeclaration cCOMIC_SANS_MSEnumLiteralDeclaration = (EnumLiteralDeclaration)rule.eContents().get(1);
		private final Keyword cCOMIC_SANS_MSCOMIC_SANS_MSKeyword_0 = (Keyword)cCOMIC_SANS_MSEnumLiteralDeclaration.eContents().get(0);
		
		//enum FontStyle:
		//	COMIC_SANS_MS;
		public EnumRule getRule() { return rule; }
		
		//COMIC_SANS_MS
		public EnumLiteralDeclaration getCOMIC_SANS_MSEnumLiteralDeclaration() { return cCOMIC_SANS_MSEnumLiteralDeclaration; }
		
		//'COMIC_SANS_MS'
		public Keyword getCOMIC_SANS_MSCOMIC_SANS_MSKeyword_0() { return cCOMIC_SANS_MSCOMIC_SANS_MSKeyword_0; }
	}
	
	private final MovieElements pMovie;
	private final AudioElementElements pAudioElement;
	private final VideoElementElements pVideoElement;
	private final TextAreaElements pTextArea;
	private final StartingMomentElements pStartingMoment;
	private final AnimationElements pAnimation;
	private final EStringElements pEString;
	private final SubtitleElements pSubtitle;
	private final AudioElements pAudio;
	private final AudioClipElements pAudioClip;
	private final ClipElements pClip;
	private final TitleElements pTitle;
	private final VideoElements pVideo;
	private final RelativeMomentElements pRelativeMoment;
	private final OperationMomentElements eOperationMoment;
	private final AbsoluteMomentElements pAbsoluteMoment;
	private final StartingMoment_ImplElements pStartingMoment_Impl;
	private final TransitionElements pTransition;
	private final MomentElements eMoment;
	private final TextArea_ImplElements pTextArea_Impl;
	private final ColorElements eColor;
	private final FontElements pFont;
	private final FontStyleElements eFontStyle;
	private final TextAreaDynamicElements pTextAreaDynamic;
	private final FadeInElements pFadeIn;
	private final FadeOutElements pFadeOut;
	private final EDoubleElements pEDouble;
	private final EIntElements pEInt;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public VideoMontageGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pMovie = new MovieElements();
		this.pAudioElement = new AudioElementElements();
		this.pVideoElement = new VideoElementElements();
		this.pTextArea = new TextAreaElements();
		this.pStartingMoment = new StartingMomentElements();
		this.pAnimation = new AnimationElements();
		this.pEString = new EStringElements();
		this.pSubtitle = new SubtitleElements();
		this.pAudio = new AudioElements();
		this.pAudioClip = new AudioClipElements();
		this.pClip = new ClipElements();
		this.pTitle = new TitleElements();
		this.pVideo = new VideoElements();
		this.pRelativeMoment = new RelativeMomentElements();
		this.eOperationMoment = new OperationMomentElements();
		this.pAbsoluteMoment = new AbsoluteMomentElements();
		this.pStartingMoment_Impl = new StartingMoment_ImplElements();
		this.pTransition = new TransitionElements();
		this.eMoment = new MomentElements();
		this.pTextArea_Impl = new TextArea_ImplElements();
		this.eColor = new ColorElements();
		this.pFont = new FontElements();
		this.eFontStyle = new FontStyleElements();
		this.pTextAreaDynamic = new TextAreaDynamicElements();
		this.pFadeIn = new FadeInElements();
		this.pFadeOut = new FadeOutElements();
		this.pEDouble = new EDoubleElements();
		this.pEInt = new EIntElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.svjd.VideoMontage".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Movie:
	//	'Movie' title=EString
	//	'{'
	//	videoelement+=VideoElement videoelement+=VideoElement* (audioelement+=AudioElement audioelement+=AudioElement*)?
	//	(subtitle+=Subtitle subtitle+=Subtitle*)?
	//	'}';
	public MovieElements getMovieAccess() {
		return pMovie;
	}
	
	public ParserRule getMovieRule() {
		return getMovieAccess().getRule();
	}
	
	//AudioElement:
	//	'audioElement' (Audio | AudioClip);
	public AudioElementElements getAudioElementAccess() {
		return pAudioElement;
	}
	
	public ParserRule getAudioElementRule() {
		return getAudioElementAccess().getRule();
	}
	
	//VideoElement:
	//	'videoElement' (Title | Clip | Video);
	public VideoElementElements getVideoElementAccess() {
		return pVideoElement;
	}
	
	public ParserRule getVideoElementRule() {
		return getVideoElementAccess().getRule();
	}
	
	//TextArea:
	//	TextArea_Impl | TextAreaDynamic;
	public TextAreaElements getTextAreaAccess() {
		return pTextArea;
	}
	
	public ParserRule getTextAreaRule() {
		return getTextAreaAccess().getRule();
	}
	
	//StartingMoment:
	//	StartingMoment_Impl | RelativeMoment | AbsoluteMoment;
	public StartingMomentElements getStartingMomentAccess() {
		return pStartingMoment;
	}
	
	public ParserRule getStartingMomentRule() {
		return getStartingMomentAccess().getRule();
	}
	
	//Animation:
	//	FadeIn | FadeOut;
	public AnimationElements getAnimationAccess() {
		return pAnimation;
	}
	
	public ParserRule getAnimationRule() {
		return getAnimationAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Subtitle:
	//	'Subtitle'
	//	name=EString 'start' ':' startingmoment=StartingMoment
	//	'{' ('duration' duration=EDouble)?
	//	'textArea' textarea=TextArea
	//	'}';
	public SubtitleElements getSubtitleAccess() {
		return pSubtitle;
	}
	
	public ParserRule getSubtitleRule() {
		return getSubtitleAccess().getRule();
	}
	
	//Audio:
	//	'Audio'
	//	name=EString 'start' ':' startingmoment=StartingMoment
	//	'{' ('path' path=EString)? ('transition' transition=Transition)?
	//	'}';
	public AudioElements getAudioAccess() {
		return pAudio;
	}
	
	public ParserRule getAudioRule() {
		return getAudioAccess().getRule();
	}
	
	//AudioClip:
	//	'AudioClip'
	//	name=EString 'start' ':' startingmoment=StartingMoment
	//	'{' ('volume' volume=EDouble)? ('startCut' startCut=EDouble) ('endCut' endCut=EDouble) ('transition'
	//	transition=Transition)?
	//	'audio' audio+=[Audio]*
	//	'}';
	public AudioClipElements getAudioClipAccess() {
		return pAudioClip;
	}
	
	public ParserRule getAudioClipRule() {
		return getAudioClipAccess().getRule();
	}
	
	//Clip:
	//	'Clip'
	//	name=EString
	//	'{' ('startCut' startCut=EDouble)? ('endCut' endCut=EDouble)?
	//	'video' video+=[Video]*
	//	'}';
	public ClipElements getClipAccess() {
		return pClip;
	}
	
	public ParserRule getClipRule() {
		return getClipAccess().getRule();
	}
	
	//Title:
	//	'Title'
	//	name=EString
	//	'{' ('duration' duration=EDouble)? ('backgroundColor' backgroundColor=Color)?
	//	'textArea' textarea=TextArea
	//	'}';
	public TitleElements getTitleAccess() {
		return pTitle;
	}
	
	public ParserRule getTitleRule() {
		return getTitleAccess().getRule();
	}
	
	//Video:
	//	name=EString ('path' path=EString);
	public VideoElements getVideoAccess() {
		return pVideo;
	}
	
	public ParserRule getVideoRule() {
		return getVideoAccess().getRule();
	}
	
	//RelativeMoment:
	//	{RelativeMoment} moment=Moment? 'of' element=[Element] (operationMoment=OperationMoment value=EDouble)?;
	public RelativeMomentElements getRelativeMomentAccess() {
		return pRelativeMoment;
	}
	
	public ParserRule getRelativeMomentRule() {
		return getRelativeMomentAccess().getRule();
	}
	
	//enum OperationMoment:
	//	Addition='+' |
	//	Soustraction="-";
	public OperationMomentElements getOperationMomentAccess() {
		return eOperationMoment;
	}
	
	public EnumRule getOperationMomentRule() {
		return getOperationMomentAccess().getRule();
	}
	
	//AbsoluteMoment:
	//	{AbsoluteMoment} ('time' time=EDouble)?;
	public AbsoluteMomentElements getAbsoluteMomentAccess() {
		return pAbsoluteMoment;
	}
	
	public ParserRule getAbsoluteMomentRule() {
		return getAbsoluteMomentAccess().getRule();
	}
	
	//StartingMoment_Impl StartingMoment:
	//	{StartingMoment}
	//	'StartingMoment';
	public StartingMoment_ImplElements getStartingMoment_ImplAccess() {
		return pStartingMoment_Impl;
	}
	
	public ParserRule getStartingMoment_ImplRule() {
		return getStartingMoment_ImplAccess().getRule();
	}
	
	//Transition:
	//	'Transition'
	//	'{' ('duration' duration=EDouble)?
	//	'audioElement' audioelement=AudioElement
	//	'}';
	public TransitionElements getTransitionAccess() {
		return pTransition;
	}
	
	public ParserRule getTransitionRule() {
		return getTransitionAccess().getRule();
	}
	
	//enum Moment:
	//	starting | ending;
	public MomentElements getMomentAccess() {
		return eMoment;
	}
	
	public EnumRule getMomentRule() {
		return getMomentAccess().getRule();
	}
	
	//TextArea_Impl TextArea:
	//	'TextArea'
	//	'{' ('x' x=EInt)? ('y' y=EInt)? ('width' width=EDouble)? ('height' height=EDouble)? ('text' text=EString) ('font'
	//	font=[Font])? ('animation' animation+=Animation animation+=Animation*)?
	//	'}';
	public TextArea_ImplElements getTextArea_ImplAccess() {
		return pTextArea_Impl;
	}
	
	public ParserRule getTextArea_ImplRule() {
		return getTextArea_ImplAccess().getRule();
	}
	
	//enum Color:
	//	BLACK;
	public ColorElements getColorAccess() {
		return eColor;
	}
	
	public EnumRule getColorRule() {
		return getColorAccess().getRule();
	}
	
	//Font:
	//	{Font} fontStyle=FontStyle ('length' length=EString);
	public FontElements getFontAccess() {
		return pFont;
	}
	
	public ParserRule getFontRule() {
		return getFontAccess().getRule();
	}
	
	//enum FontStyle:
	//	COMIC_SANS_MS;
	public FontStyleElements getFontStyleAccess() {
		return eFontStyle;
	}
	
	public EnumRule getFontStyleRule() {
		return getFontStyleAccess().getRule();
	}
	
	//TextAreaDynamic:
	//	'TextAreaDynamic'
	//	'{' ('x' x=EInt)? ('y' y=EInt)? ('width' width=EDouble)? ('height' height=EDouble)? ('text' text=EString)? ('textSrc'
	//	textSrc=EString)? ('line' line=EInt)?
	//	'font' font=[Font|EString] ('animation' animation+=Animation animation+=Animation*)?
	//	'}';
	public TextAreaDynamicElements getTextAreaDynamicAccess() {
		return pTextAreaDynamic;
	}
	
	public ParserRule getTextAreaDynamicRule() {
		return getTextAreaDynamicAccess().getRule();
	}
	
	//FadeIn:
	//	{FadeIn}
	//	'FadeIn'
	//	'{' ('duration' duration=EDouble)?
	//	'}';
	public FadeInElements getFadeInAccess() {
		return pFadeIn;
	}
	
	public ParserRule getFadeInRule() {
		return getFadeInAccess().getRule();
	}
	
	//FadeOut:
	//	{FadeOut}
	//	'FadeOut'
	//	'{' ('duration' duration=EDouble)?
	//	'}';
	public FadeOutElements getFadeOutAccess() {
		return pFadeOut;
	}
	
	public ParserRule getFadeOutRule() {
		return getFadeOutAccess().getRule();
	}
	
	//EDouble ecore::EDouble:
	//	'-'? INT? '.' INT (('E' | 'e') '-'? INT)?;
	public EDoubleElements getEDoubleAccess() {
		return pEDouble;
	}
	
	public ParserRule getEDoubleRule() {
		return getEDoubleAccess().getRule();
	}
	
	//EInt ecore::EInt:
	//	'-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
