/*
 * generated by Xtext 2.24.0
 */
package org.xtext.svjd.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.svjd.VideoMontage.ui.internal.VideoMontageActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class VideoMontageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(VideoMontageActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		VideoMontageActivator activator = VideoMontageActivator.getInstance();
		return activator != null ? activator.getInjector(VideoMontageActivator.ORG_XTEXT_SVJD_VIDEOMONTAGE) : null;
	}

}
