/*
 * generated by Xtext 2.21.0
 */
package org.xtext.svjd.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.svjd.VideoMontage.ui.internal.VideoMontageActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class VideoMontageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(VideoMontageActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		VideoMontageActivator activator = VideoMontageActivator.getInstance();
		return activator != null ? activator.getInjector(VideoMontageActivator.ORG_XTEXT_SVJD_VIDEOMONTAGE) : null;
	}

}
