/*
 * generated by Xtext 2.24.0
 */
package org.xtext.svjd.ide;


/**
 * Use this class to register ide components.
 */
public class VideoMontageSVJDIdeModule extends AbstractVideoMontageSVJDIdeModule {
}
