/**
 * generated by Xtext 2.24.0
 */
package org.xtext.svjd.videoMontageSVJD;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Animation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.svjd.videoMontageSVJD.Animation#getDuration <em>Duration</em>}</li>
 * </ul>
 *
 * @see org.xtext.svjd.videoMontageSVJD.VideoMontageSVJDPackage#getAnimation()
 * @model
 * @generated
 */
public interface Animation extends EObject
{
  /**
   * Returns the value of the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Duration</em>' attribute.
   * @see #setDuration(double)
   * @see org.xtext.svjd.videoMontageSVJD.VideoMontageSVJDPackage#getAnimation_Duration()
   * @model
   * @generated
   */
  double getDuration();

  /**
   * Sets the value of the '{@link org.xtext.svjd.videoMontageSVJD.Animation#getDuration <em>Duration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Duration</em>' attribute.
   * @see #getDuration()
   * @generated
   */
  void setDuration(double value);

} // Animation
