/**
 * generated by Xtext 2.24.0
 */
package org.xtext.svjd.videoMontageSVJD;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Clip</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.svjd.videoMontageSVJD.Clip#getStartCut <em>Start Cut</em>}</li>
 *   <li>{@link org.xtext.svjd.videoMontageSVJD.Clip#getEndCut <em>End Cut</em>}</li>
 *   <li>{@link org.xtext.svjd.videoMontageSVJD.Clip#getVideo <em>Video</em>}</li>
 * </ul>
 *
 * @see org.xtext.svjd.videoMontageSVJD.VideoMontageSVJDPackage#getClip()
 * @model
 * @generated
 */
public interface Clip extends VideoElement
{
  /**
   * Returns the value of the '<em><b>Start Cut</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start Cut</em>' attribute.
   * @see #setStartCut(double)
   * @see org.xtext.svjd.videoMontageSVJD.VideoMontageSVJDPackage#getClip_StartCut()
   * @model
   * @generated
   */
  double getStartCut();

  /**
   * Sets the value of the '{@link org.xtext.svjd.videoMontageSVJD.Clip#getStartCut <em>Start Cut</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start Cut</em>' attribute.
   * @see #getStartCut()
   * @generated
   */
  void setStartCut(double value);

  /**
   * Returns the value of the '<em><b>End Cut</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>End Cut</em>' attribute.
   * @see #setEndCut(double)
   * @see org.xtext.svjd.videoMontageSVJD.VideoMontageSVJDPackage#getClip_EndCut()
   * @model
   * @generated
   */
  double getEndCut();

  /**
   * Sets the value of the '{@link org.xtext.svjd.videoMontageSVJD.Clip#getEndCut <em>End Cut</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End Cut</em>' attribute.
   * @see #getEndCut()
   * @generated
   */
  void setEndCut(double value);

  /**
   * Returns the value of the '<em><b>Video</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Video</em>' reference.
   * @see #setVideo(Video)
   * @see org.xtext.svjd.videoMontageSVJD.VideoMontageSVJDPackage#getClip_Video()
   * @model
   * @generated
   */
  Video getVideo();

  /**
   * Sets the value of the '{@link org.xtext.svjd.videoMontageSVJD.Clip#getVideo <em>Video</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Video</em>' reference.
   * @see #getVideo()
   * @generated
   */
  void setVideo(Video value);

} // Clip
