/**
 * generated by Xtext 2.24.0
 */
package org.xtext.svjd.videoMontageSVJD;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fade Out</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.svjd.videoMontageSVJD.VideoMontageSVJDPackage#getFadeOut()
 * @model
 * @generated
 */
public interface FadeOut extends Animation
{
} // FadeOut
