/**
 * generated by Xtext 2.24.0
 */
package org.xtext.svjd.videoMontageSVJD;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Starting Moment</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.svjd.videoMontageSVJD.VideoMontageSVJDPackage#getStartingMoment()
 * @model
 * @generated
 */
public interface StartingMoment extends EObject
{
} // StartingMoment
