/**
 * generated by Xtext 2.24.0
 */
package org.xtext.svjd.videoMontageSVJD;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Subtitle</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.svjd.videoMontageSVJD.Subtitle#getStartingmoment <em>Startingmoment</em>}</li>
 *   <li>{@link org.xtext.svjd.videoMontageSVJD.Subtitle#getDuration <em>Duration</em>}</li>
 *   <li>{@link org.xtext.svjd.videoMontageSVJD.Subtitle#getTextarea <em>Textarea</em>}</li>
 * </ul>
 *
 * @see org.xtext.svjd.videoMontageSVJD.VideoMontageSVJDPackage#getSubtitle()
 * @model
 * @generated
 */
public interface Subtitle extends Element
{
  /**
   * Returns the value of the '<em><b>Startingmoment</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Startingmoment</em>' containment reference.
   * @see #setStartingmoment(StartingMoment)
   * @see org.xtext.svjd.videoMontageSVJD.VideoMontageSVJDPackage#getSubtitle_Startingmoment()
   * @model containment="true"
   * @generated
   */
  StartingMoment getStartingmoment();

  /**
   * Sets the value of the '{@link org.xtext.svjd.videoMontageSVJD.Subtitle#getStartingmoment <em>Startingmoment</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Startingmoment</em>' containment reference.
   * @see #getStartingmoment()
   * @generated
   */
  void setStartingmoment(StartingMoment value);

  /**
   * Returns the value of the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Duration</em>' attribute.
   * @see #setDuration(double)
   * @see org.xtext.svjd.videoMontageSVJD.VideoMontageSVJDPackage#getSubtitle_Duration()
   * @model
   * @generated
   */
  double getDuration();

  /**
   * Sets the value of the '{@link org.xtext.svjd.videoMontageSVJD.Subtitle#getDuration <em>Duration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Duration</em>' attribute.
   * @see #getDuration()
   * @generated
   */
  void setDuration(double value);

  /**
   * Returns the value of the '<em><b>Textarea</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Textarea</em>' containment reference.
   * @see #setTextarea(TextArea)
   * @see org.xtext.svjd.videoMontageSVJD.VideoMontageSVJDPackage#getSubtitle_Textarea()
   * @model containment="true"
   * @generated
   */
  TextArea getTextarea();

  /**
   * Sets the value of the '{@link org.xtext.svjd.videoMontageSVJD.Subtitle#getTextarea <em>Textarea</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Textarea</em>' containment reference.
   * @see #getTextarea()
   * @generated
   */
  void setTextarea(TextArea value);

} // Subtitle
