/**
 * generated by Xtext 2.24.0
 */
package org.xtext.svjd.videoMontageSVJD;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Text Area Dynamic</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.svjd.videoMontageSVJD.TextAreaDynamic#getTextSrc <em>Text Src</em>}</li>
 *   <li>{@link org.xtext.svjd.videoMontageSVJD.TextAreaDynamic#getLine <em>Line</em>}</li>
 * </ul>
 *
 * @see org.xtext.svjd.videoMontageSVJD.VideoMontageSVJDPackage#getTextAreaDynamic()
 * @model
 * @generated
 */
public interface TextAreaDynamic extends TextArea
{
  /**
   * Returns the value of the '<em><b>Text Src</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text Src</em>' attribute.
   * @see #setTextSrc(String)
   * @see org.xtext.svjd.videoMontageSVJD.VideoMontageSVJDPackage#getTextAreaDynamic_TextSrc()
   * @model
   * @generated
   */
  String getTextSrc();

  /**
   * Sets the value of the '{@link org.xtext.svjd.videoMontageSVJD.TextAreaDynamic#getTextSrc <em>Text Src</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text Src</em>' attribute.
   * @see #getTextSrc()
   * @generated
   */
  void setTextSrc(String value);

  /**
   * Returns the value of the '<em><b>Line</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Line</em>' attribute.
   * @see #setLine(int)
   * @see org.xtext.svjd.videoMontageSVJD.VideoMontageSVJDPackage#getTextAreaDynamic_Line()
   * @model
   * @generated
   */
  int getLine();

  /**
   * Sets the value of the '{@link org.xtext.svjd.videoMontageSVJD.TextAreaDynamic#getLine <em>Line</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Line</em>' attribute.
   * @see #getLine()
   * @generated
   */
  void setLine(int value);

} // TextAreaDynamic
