/**
 * generated by Xtext 2.24.0
 */
package org.xtext.svjd.videoMontageSVJD;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Title</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.svjd.videoMontageSVJD.Title#getDuration <em>Duration</em>}</li>
 *   <li>{@link org.xtext.svjd.videoMontageSVJD.Title#getBackgroundColor <em>Background Color</em>}</li>
 *   <li>{@link org.xtext.svjd.videoMontageSVJD.Title#getTextarea <em>Textarea</em>}</li>
 * </ul>
 *
 * @see org.xtext.svjd.videoMontageSVJD.VideoMontageSVJDPackage#getTitle()
 * @model
 * @generated
 */
public interface Title extends VideoElement
{
  /**
   * Returns the value of the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Duration</em>' attribute.
   * @see #setDuration(double)
   * @see org.xtext.svjd.videoMontageSVJD.VideoMontageSVJDPackage#getTitle_Duration()
   * @model
   * @generated
   */
  double getDuration();

  /**
   * Sets the value of the '{@link org.xtext.svjd.videoMontageSVJD.Title#getDuration <em>Duration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Duration</em>' attribute.
   * @see #getDuration()
   * @generated
   */
  void setDuration(double value);

  /**
   * Returns the value of the '<em><b>Background Color</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.svjd.videoMontageSVJD.Color}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Background Color</em>' attribute.
   * @see org.xtext.svjd.videoMontageSVJD.Color
   * @see #setBackgroundColor(Color)
   * @see org.xtext.svjd.videoMontageSVJD.VideoMontageSVJDPackage#getTitle_BackgroundColor()
   * @model
   * @generated
   */
  Color getBackgroundColor();

  /**
   * Sets the value of the '{@link org.xtext.svjd.videoMontageSVJD.Title#getBackgroundColor <em>Background Color</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Background Color</em>' attribute.
   * @see org.xtext.svjd.videoMontageSVJD.Color
   * @see #getBackgroundColor()
   * @generated
   */
  void setBackgroundColor(Color value);

  /**
   * Returns the value of the '<em><b>Textarea</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Textarea</em>' containment reference.
   * @see #setTextarea(TextArea)
   * @see org.xtext.svjd.videoMontageSVJD.VideoMontageSVJDPackage#getTitle_Textarea()
   * @model containment="true"
   * @generated
   */
  TextArea getTextarea();

  /**
   * Sets the value of the '{@link org.xtext.svjd.videoMontageSVJD.Title#getTextarea <em>Textarea</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Textarea</em>' containment reference.
   * @see #getTextarea()
   * @generated
   */
  void setTextarea(TextArea value);

} // Title
