/**
 * generated by Xtext 2.24.0
 */
package org.xtext.svjd.videoMontageSVJD;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.svjd.videoMontageSVJD.VideoMontageSVJDFactory
 * @model kind="package"
 * @generated
 */
public interface VideoMontageSVJDPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "videoMontageSVJD";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/svjd/VideoMontageSVJD";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "videoMontageSVJD";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  VideoMontageSVJDPackage eINSTANCE = org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.svjd.videoMontageSVJD.impl.MovieImpl <em>Movie</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.svjd.videoMontageSVJD.impl.MovieImpl
   * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getMovie()
   * @generated
   */
  int MOVIE = 0;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVIE__TITLE = 0;

  /**
   * The feature id for the '<em><b>Videoelement</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVIE__VIDEOELEMENT = 1;

  /**
   * The feature id for the '<em><b>Audioelement</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVIE__AUDIOELEMENT = 2;

  /**
   * The feature id for the '<em><b>Subtitle</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVIE__SUBTITLE = 3;

  /**
   * The feature id for the '<em><b>Video Timeline</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVIE__VIDEO_TIMELINE = 4;

  /**
   * The number of structural features of the '<em>Movie</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVIE_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.svjd.videoMontageSVJD.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.svjd.videoMontageSVJD.impl.ElementImpl
   * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.svjd.videoMontageSVJD.impl.AudioElementImpl <em>Audio Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.svjd.videoMontageSVJD.impl.AudioElementImpl
   * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getAudioElement()
   * @generated
   */
  int AUDIO_ELEMENT = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUDIO_ELEMENT__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Transition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUDIO_ELEMENT__TRANSITION = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Audio Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUDIO_ELEMENT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.svjd.videoMontageSVJD.impl.VideoElementImpl <em>Video Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.svjd.videoMontageSVJD.impl.VideoElementImpl
   * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getVideoElement()
   * @generated
   */
  int VIDEO_ELEMENT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_ELEMENT__NAME = ELEMENT__NAME;

  /**
   * The number of structural features of the '<em>Video Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_ELEMENT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.svjd.videoMontageSVJD.impl.VideoTimeLineImpl <em>Video Time Line</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.svjd.videoMontageSVJD.impl.VideoTimeLineImpl
   * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getVideoTimeLine()
   * @generated
   */
  int VIDEO_TIME_LINE = 4;

  /**
   * The feature id for the '<em><b>Videos</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_TIME_LINE__VIDEOS = 0;

  /**
   * The number of structural features of the '<em>Video Time Line</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_TIME_LINE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.svjd.videoMontageSVJD.impl.TextAreaImpl <em>Text Area</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.svjd.videoMontageSVJD.impl.TextAreaImpl
   * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getTextArea()
   * @generated
   */
  int TEXT_AREA = 5;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_AREA__X = 0;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_AREA__Y = 1;

  /**
   * The feature id for the '<em><b>Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_AREA__WIDTH = 2;

  /**
   * The feature id for the '<em><b>Height</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_AREA__HEIGHT = 3;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_AREA__TEXT = 4;

  /**
   * The feature id for the '<em><b>Font</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_AREA__FONT = 5;

  /**
   * The feature id for the '<em><b>Animation</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_AREA__ANIMATION = 6;

  /**
   * The number of structural features of the '<em>Text Area</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_AREA_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link org.xtext.svjd.videoMontageSVJD.impl.StartingMomentImpl <em>Starting Moment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.svjd.videoMontageSVJD.impl.StartingMomentImpl
   * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getStartingMoment()
   * @generated
   */
  int STARTING_MOMENT = 6;

  /**
   * The number of structural features of the '<em>Starting Moment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STARTING_MOMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.svjd.videoMontageSVJD.impl.AnimationImpl <em>Animation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.svjd.videoMontageSVJD.impl.AnimationImpl
   * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getAnimation()
   * @generated
   */
  int ANIMATION = 7;

  /**
   * The feature id for the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANIMATION__DURATION = 0;

  /**
   * The number of structural features of the '<em>Animation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANIMATION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.svjd.videoMontageSVJD.impl.SubtitleImpl <em>Subtitle</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.svjd.videoMontageSVJD.impl.SubtitleImpl
   * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getSubtitle()
   * @generated
   */
  int SUBTITLE = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBTITLE__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Startingmoment</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBTITLE__STARTINGMOMENT = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBTITLE__DURATION = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Textarea</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBTITLE__TEXTAREA = ELEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Subtitle</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBTITLE_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.svjd.videoMontageSVJD.impl.AudioImpl <em>Audio</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.svjd.videoMontageSVJD.impl.AudioImpl
   * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getAudio()
   * @generated
   */
  int AUDIO = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUDIO__NAME = AUDIO_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Transition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUDIO__TRANSITION = AUDIO_ELEMENT__TRANSITION;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUDIO__PATH = AUDIO_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Audio</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUDIO_FEATURE_COUNT = AUDIO_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.svjd.videoMontageSVJD.impl.AudioClipImpl <em>Audio Clip</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.svjd.videoMontageSVJD.impl.AudioClipImpl
   * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getAudioClip()
   * @generated
   */
  int AUDIO_CLIP = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUDIO_CLIP__NAME = AUDIO_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Transition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUDIO_CLIP__TRANSITION = AUDIO_ELEMENT__TRANSITION;

  /**
   * The feature id for the '<em><b>Startingmoment</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUDIO_CLIP__STARTINGMOMENT = AUDIO_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Volume</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUDIO_CLIP__VOLUME = AUDIO_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Start Cut</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUDIO_CLIP__START_CUT = AUDIO_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>End Cut</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUDIO_CLIP__END_CUT = AUDIO_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Audio</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUDIO_CLIP__AUDIO = AUDIO_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Audio Clip</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUDIO_CLIP_FEATURE_COUNT = AUDIO_ELEMENT_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link org.xtext.svjd.videoMontageSVJD.impl.ClipImpl <em>Clip</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.svjd.videoMontageSVJD.impl.ClipImpl
   * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getClip()
   * @generated
   */
  int CLIP = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLIP__NAME = VIDEO_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Start Cut</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLIP__START_CUT = VIDEO_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>End Cut</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLIP__END_CUT = VIDEO_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Video</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLIP__VIDEO = VIDEO_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Clip</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLIP_FEATURE_COUNT = VIDEO_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.svjd.videoMontageSVJD.impl.TitleImpl <em>Title</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.svjd.videoMontageSVJD.impl.TitleImpl
   * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getTitle()
   * @generated
   */
  int TITLE = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TITLE__NAME = VIDEO_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TITLE__DURATION = VIDEO_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Background Color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TITLE__BACKGROUND_COLOR = VIDEO_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Textarea</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TITLE__TEXTAREA = VIDEO_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Title</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TITLE_FEATURE_COUNT = VIDEO_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.svjd.videoMontageSVJD.impl.VideoImpl <em>Video</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.svjd.videoMontageSVJD.impl.VideoImpl
   * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getVideo()
   * @generated
   */
  int VIDEO = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO__NAME = VIDEO_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO__PATH = VIDEO_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Video</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_FEATURE_COUNT = VIDEO_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.svjd.videoMontageSVJD.impl.RelativeMomentImpl <em>Relative Moment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.svjd.videoMontageSVJD.impl.RelativeMomentImpl
   * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getRelativeMoment()
   * @generated
   */
  int RELATIVE_MOMENT = 14;

  /**
   * The feature id for the '<em><b>Moment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIVE_MOMENT__MOMENT = STARTING_MOMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Element</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIVE_MOMENT__ELEMENT = STARTING_MOMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Operation Moment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIVE_MOMENT__OPERATION_MOMENT = STARTING_MOMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIVE_MOMENT__VALUE = STARTING_MOMENT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Relative Moment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIVE_MOMENT_FEATURE_COUNT = STARTING_MOMENT_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.xtext.svjd.videoMontageSVJD.impl.AbsoluteMomentImpl <em>Absolute Moment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.svjd.videoMontageSVJD.impl.AbsoluteMomentImpl
   * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getAbsoluteMoment()
   * @generated
   */
  int ABSOLUTE_MOMENT = 15;

  /**
   * The feature id for the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSOLUTE_MOMENT__TIME = STARTING_MOMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Absolute Moment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSOLUTE_MOMENT_FEATURE_COUNT = STARTING_MOMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.svjd.videoMontageSVJD.impl.TransitionImpl <em>Transition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.svjd.videoMontageSVJD.impl.TransitionImpl
   * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getTransition()
   * @generated
   */
  int TRANSITION = 16;

  /**
   * The feature id for the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__DURATION = 0;

  /**
   * The feature id for the '<em><b>Audioelement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__AUDIOELEMENT = 1;

  /**
   * The number of structural features of the '<em>Transition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.svjd.videoMontageSVJD.impl.FontImpl <em>Font</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.svjd.videoMontageSVJD.impl.FontImpl
   * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getFont()
   * @generated
   */
  int FONT = 17;

  /**
   * The feature id for the '<em><b>Font Style</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FONT__FONT_STYLE = 0;

  /**
   * The feature id for the '<em><b>Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FONT__LENGTH = 1;

  /**
   * The number of structural features of the '<em>Font</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FONT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.svjd.videoMontageSVJD.impl.TextAreaDynamicImpl <em>Text Area Dynamic</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.svjd.videoMontageSVJD.impl.TextAreaDynamicImpl
   * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getTextAreaDynamic()
   * @generated
   */
  int TEXT_AREA_DYNAMIC = 18;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_AREA_DYNAMIC__X = TEXT_AREA__X;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_AREA_DYNAMIC__Y = TEXT_AREA__Y;

  /**
   * The feature id for the '<em><b>Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_AREA_DYNAMIC__WIDTH = TEXT_AREA__WIDTH;

  /**
   * The feature id for the '<em><b>Height</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_AREA_DYNAMIC__HEIGHT = TEXT_AREA__HEIGHT;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_AREA_DYNAMIC__TEXT = TEXT_AREA__TEXT;

  /**
   * The feature id for the '<em><b>Font</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_AREA_DYNAMIC__FONT = TEXT_AREA__FONT;

  /**
   * The feature id for the '<em><b>Animation</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_AREA_DYNAMIC__ANIMATION = TEXT_AREA__ANIMATION;

  /**
   * The feature id for the '<em><b>Text Src</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_AREA_DYNAMIC__TEXT_SRC = TEXT_AREA_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Line</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_AREA_DYNAMIC__LINE = TEXT_AREA_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Text Area Dynamic</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_AREA_DYNAMIC_FEATURE_COUNT = TEXT_AREA_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.svjd.videoMontageSVJD.impl.ScrollingTextImpl <em>Scrolling Text</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.svjd.videoMontageSVJD.impl.ScrollingTextImpl
   * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getScrollingText()
   * @generated
   */
  int SCROLLING_TEXT = 19;

  /**
   * The feature id for the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCROLLING_TEXT__DURATION = ANIMATION__DURATION;

  /**
   * The feature id for the '<em><b>Speed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCROLLING_TEXT__SPEED = ANIMATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Scrolling Text</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCROLLING_TEXT_FEATURE_COUNT = ANIMATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.svjd.videoMontageSVJD.impl.FadeInImpl <em>Fade In</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.svjd.videoMontageSVJD.impl.FadeInImpl
   * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getFadeIn()
   * @generated
   */
  int FADE_IN = 20;

  /**
   * The feature id for the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FADE_IN__DURATION = ANIMATION__DURATION;

  /**
   * The number of structural features of the '<em>Fade In</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FADE_IN_FEATURE_COUNT = ANIMATION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.svjd.videoMontageSVJD.impl.FadeOutImpl <em>Fade Out</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.svjd.videoMontageSVJD.impl.FadeOutImpl
   * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getFadeOut()
   * @generated
   */
  int FADE_OUT = 21;

  /**
   * The feature id for the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FADE_OUT__DURATION = ANIMATION__DURATION;

  /**
   * The number of structural features of the '<em>Fade Out</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FADE_OUT_FEATURE_COUNT = ANIMATION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.svjd.videoMontageSVJD.OperationMoment <em>Operation Moment</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.svjd.videoMontageSVJD.OperationMoment
   * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getOperationMoment()
   * @generated
   */
  int OPERATION_MOMENT = 22;

  /**
   * The meta object id for the '{@link org.xtext.svjd.videoMontageSVJD.Moment <em>Moment</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.svjd.videoMontageSVJD.Moment
   * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getMoment()
   * @generated
   */
  int MOMENT = 23;

  /**
   * The meta object id for the '{@link org.xtext.svjd.videoMontageSVJD.Color <em>Color</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.svjd.videoMontageSVJD.Color
   * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getColor()
   * @generated
   */
  int COLOR = 24;

  /**
   * The meta object id for the '{@link org.xtext.svjd.videoMontageSVJD.FontStyle <em>Font Style</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.svjd.videoMontageSVJD.FontStyle
   * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getFontStyle()
   * @generated
   */
  int FONT_STYLE = 25;


  /**
   * Returns the meta object for class '{@link org.xtext.svjd.videoMontageSVJD.Movie <em>Movie</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Movie</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.Movie
   * @generated
   */
  EClass getMovie();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.svjd.videoMontageSVJD.Movie#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.Movie#getTitle()
   * @see #getMovie()
   * @generated
   */
  EAttribute getMovie_Title();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.svjd.videoMontageSVJD.Movie#getVideoelement <em>Videoelement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Videoelement</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.Movie#getVideoelement()
   * @see #getMovie()
   * @generated
   */
  EReference getMovie_Videoelement();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.svjd.videoMontageSVJD.Movie#getAudioelement <em>Audioelement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Audioelement</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.Movie#getAudioelement()
   * @see #getMovie()
   * @generated
   */
  EReference getMovie_Audioelement();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.svjd.videoMontageSVJD.Movie#getSubtitle <em>Subtitle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Subtitle</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.Movie#getSubtitle()
   * @see #getMovie()
   * @generated
   */
  EReference getMovie_Subtitle();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.svjd.videoMontageSVJD.Movie#getVideoTimeline <em>Video Timeline</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Video Timeline</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.Movie#getVideoTimeline()
   * @see #getMovie()
   * @generated
   */
  EReference getMovie_VideoTimeline();

  /**
   * Returns the meta object for class '{@link org.xtext.svjd.videoMontageSVJD.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.svjd.videoMontageSVJD.Element#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.Element#getName()
   * @see #getElement()
   * @generated
   */
  EAttribute getElement_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.svjd.videoMontageSVJD.AudioElement <em>Audio Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Audio Element</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.AudioElement
   * @generated
   */
  EClass getAudioElement();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.svjd.videoMontageSVJD.AudioElement#getTransition <em>Transition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Transition</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.AudioElement#getTransition()
   * @see #getAudioElement()
   * @generated
   */
  EReference getAudioElement_Transition();

  /**
   * Returns the meta object for class '{@link org.xtext.svjd.videoMontageSVJD.VideoElement <em>Video Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Video Element</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.VideoElement
   * @generated
   */
  EClass getVideoElement();

  /**
   * Returns the meta object for class '{@link org.xtext.svjd.videoMontageSVJD.VideoTimeLine <em>Video Time Line</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Video Time Line</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.VideoTimeLine
   * @generated
   */
  EClass getVideoTimeLine();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.svjd.videoMontageSVJD.VideoTimeLine#getVideos <em>Videos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Videos</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.VideoTimeLine#getVideos()
   * @see #getVideoTimeLine()
   * @generated
   */
  EReference getVideoTimeLine_Videos();

  /**
   * Returns the meta object for class '{@link org.xtext.svjd.videoMontageSVJD.TextArea <em>Text Area</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Text Area</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.TextArea
   * @generated
   */
  EClass getTextArea();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.svjd.videoMontageSVJD.TextArea#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.TextArea#getX()
   * @see #getTextArea()
   * @generated
   */
  EAttribute getTextArea_X();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.svjd.videoMontageSVJD.TextArea#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.TextArea#getY()
   * @see #getTextArea()
   * @generated
   */
  EAttribute getTextArea_Y();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.svjd.videoMontageSVJD.TextArea#getWidth <em>Width</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Width</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.TextArea#getWidth()
   * @see #getTextArea()
   * @generated
   */
  EAttribute getTextArea_Width();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.svjd.videoMontageSVJD.TextArea#getHeight <em>Height</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Height</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.TextArea#getHeight()
   * @see #getTextArea()
   * @generated
   */
  EAttribute getTextArea_Height();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.svjd.videoMontageSVJD.TextArea#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.TextArea#getText()
   * @see #getTextArea()
   * @generated
   */
  EAttribute getTextArea_Text();

  /**
   * Returns the meta object for the reference '{@link org.xtext.svjd.videoMontageSVJD.TextArea#getFont <em>Font</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Font</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.TextArea#getFont()
   * @see #getTextArea()
   * @generated
   */
  EReference getTextArea_Font();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.svjd.videoMontageSVJD.TextArea#getAnimation <em>Animation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Animation</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.TextArea#getAnimation()
   * @see #getTextArea()
   * @generated
   */
  EReference getTextArea_Animation();

  /**
   * Returns the meta object for class '{@link org.xtext.svjd.videoMontageSVJD.StartingMoment <em>Starting Moment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Starting Moment</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.StartingMoment
   * @generated
   */
  EClass getStartingMoment();

  /**
   * Returns the meta object for class '{@link org.xtext.svjd.videoMontageSVJD.Animation <em>Animation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Animation</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.Animation
   * @generated
   */
  EClass getAnimation();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.svjd.videoMontageSVJD.Animation#getDuration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Duration</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.Animation#getDuration()
   * @see #getAnimation()
   * @generated
   */
  EAttribute getAnimation_Duration();

  /**
   * Returns the meta object for class '{@link org.xtext.svjd.videoMontageSVJD.Subtitle <em>Subtitle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Subtitle</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.Subtitle
   * @generated
   */
  EClass getSubtitle();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.svjd.videoMontageSVJD.Subtitle#getStartingmoment <em>Startingmoment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Startingmoment</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.Subtitle#getStartingmoment()
   * @see #getSubtitle()
   * @generated
   */
  EReference getSubtitle_Startingmoment();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.svjd.videoMontageSVJD.Subtitle#getDuration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Duration</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.Subtitle#getDuration()
   * @see #getSubtitle()
   * @generated
   */
  EAttribute getSubtitle_Duration();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.svjd.videoMontageSVJD.Subtitle#getTextarea <em>Textarea</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Textarea</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.Subtitle#getTextarea()
   * @see #getSubtitle()
   * @generated
   */
  EReference getSubtitle_Textarea();

  /**
   * Returns the meta object for class '{@link org.xtext.svjd.videoMontageSVJD.Audio <em>Audio</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Audio</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.Audio
   * @generated
   */
  EClass getAudio();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.svjd.videoMontageSVJD.Audio#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.Audio#getPath()
   * @see #getAudio()
   * @generated
   */
  EAttribute getAudio_Path();

  /**
   * Returns the meta object for class '{@link org.xtext.svjd.videoMontageSVJD.AudioClip <em>Audio Clip</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Audio Clip</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.AudioClip
   * @generated
   */
  EClass getAudioClip();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.svjd.videoMontageSVJD.AudioClip#getStartingmoment <em>Startingmoment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Startingmoment</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.AudioClip#getStartingmoment()
   * @see #getAudioClip()
   * @generated
   */
  EReference getAudioClip_Startingmoment();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.svjd.videoMontageSVJD.AudioClip#getVolume <em>Volume</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Volume</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.AudioClip#getVolume()
   * @see #getAudioClip()
   * @generated
   */
  EAttribute getAudioClip_Volume();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.svjd.videoMontageSVJD.AudioClip#getStartCut <em>Start Cut</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Start Cut</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.AudioClip#getStartCut()
   * @see #getAudioClip()
   * @generated
   */
  EAttribute getAudioClip_StartCut();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.svjd.videoMontageSVJD.AudioClip#getEndCut <em>End Cut</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>End Cut</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.AudioClip#getEndCut()
   * @see #getAudioClip()
   * @generated
   */
  EAttribute getAudioClip_EndCut();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.svjd.videoMontageSVJD.AudioClip#getAudio <em>Audio</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Audio</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.AudioClip#getAudio()
   * @see #getAudioClip()
   * @generated
   */
  EReference getAudioClip_Audio();

  /**
   * Returns the meta object for class '{@link org.xtext.svjd.videoMontageSVJD.Clip <em>Clip</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Clip</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.Clip
   * @generated
   */
  EClass getClip();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.svjd.videoMontageSVJD.Clip#getStartCut <em>Start Cut</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Start Cut</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.Clip#getStartCut()
   * @see #getClip()
   * @generated
   */
  EAttribute getClip_StartCut();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.svjd.videoMontageSVJD.Clip#getEndCut <em>End Cut</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>End Cut</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.Clip#getEndCut()
   * @see #getClip()
   * @generated
   */
  EAttribute getClip_EndCut();

  /**
   * Returns the meta object for the reference '{@link org.xtext.svjd.videoMontageSVJD.Clip#getVideo <em>Video</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Video</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.Clip#getVideo()
   * @see #getClip()
   * @generated
   */
  EReference getClip_Video();

  /**
   * Returns the meta object for class '{@link org.xtext.svjd.videoMontageSVJD.Title <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Title</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.Title
   * @generated
   */
  EClass getTitle();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.svjd.videoMontageSVJD.Title#getDuration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Duration</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.Title#getDuration()
   * @see #getTitle()
   * @generated
   */
  EAttribute getTitle_Duration();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.svjd.videoMontageSVJD.Title#getBackgroundColor <em>Background Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Background Color</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.Title#getBackgroundColor()
   * @see #getTitle()
   * @generated
   */
  EAttribute getTitle_BackgroundColor();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.svjd.videoMontageSVJD.Title#getTextarea <em>Textarea</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Textarea</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.Title#getTextarea()
   * @see #getTitle()
   * @generated
   */
  EReference getTitle_Textarea();

  /**
   * Returns the meta object for class '{@link org.xtext.svjd.videoMontageSVJD.Video <em>Video</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Video</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.Video
   * @generated
   */
  EClass getVideo();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.svjd.videoMontageSVJD.Video#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.Video#getPath()
   * @see #getVideo()
   * @generated
   */
  EAttribute getVideo_Path();

  /**
   * Returns the meta object for class '{@link org.xtext.svjd.videoMontageSVJD.RelativeMoment <em>Relative Moment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Relative Moment</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.RelativeMoment
   * @generated
   */
  EClass getRelativeMoment();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.svjd.videoMontageSVJD.RelativeMoment#getMoment <em>Moment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Moment</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.RelativeMoment#getMoment()
   * @see #getRelativeMoment()
   * @generated
   */
  EAttribute getRelativeMoment_Moment();

  /**
   * Returns the meta object for the reference '{@link org.xtext.svjd.videoMontageSVJD.RelativeMoment#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Element</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.RelativeMoment#getElement()
   * @see #getRelativeMoment()
   * @generated
   */
  EReference getRelativeMoment_Element();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.svjd.videoMontageSVJD.RelativeMoment#getOperationMoment <em>Operation Moment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operation Moment</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.RelativeMoment#getOperationMoment()
   * @see #getRelativeMoment()
   * @generated
   */
  EAttribute getRelativeMoment_OperationMoment();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.svjd.videoMontageSVJD.RelativeMoment#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.RelativeMoment#getValue()
   * @see #getRelativeMoment()
   * @generated
   */
  EAttribute getRelativeMoment_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.svjd.videoMontageSVJD.AbsoluteMoment <em>Absolute Moment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Absolute Moment</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.AbsoluteMoment
   * @generated
   */
  EClass getAbsoluteMoment();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.svjd.videoMontageSVJD.AbsoluteMoment#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Time</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.AbsoluteMoment#getTime()
   * @see #getAbsoluteMoment()
   * @generated
   */
  EAttribute getAbsoluteMoment_Time();

  /**
   * Returns the meta object for class '{@link org.xtext.svjd.videoMontageSVJD.Transition <em>Transition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Transition</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.Transition
   * @generated
   */
  EClass getTransition();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.svjd.videoMontageSVJD.Transition#getDuration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Duration</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.Transition#getDuration()
   * @see #getTransition()
   * @generated
   */
  EAttribute getTransition_Duration();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.svjd.videoMontageSVJD.Transition#getAudioelement <em>Audioelement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Audioelement</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.Transition#getAudioelement()
   * @see #getTransition()
   * @generated
   */
  EReference getTransition_Audioelement();

  /**
   * Returns the meta object for class '{@link org.xtext.svjd.videoMontageSVJD.Font <em>Font</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Font</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.Font
   * @generated
   */
  EClass getFont();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.svjd.videoMontageSVJD.Font#getFontStyle <em>Font Style</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Font Style</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.Font#getFontStyle()
   * @see #getFont()
   * @generated
   */
  EAttribute getFont_FontStyle();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.svjd.videoMontageSVJD.Font#getLength <em>Length</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Length</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.Font#getLength()
   * @see #getFont()
   * @generated
   */
  EAttribute getFont_Length();

  /**
   * Returns the meta object for class '{@link org.xtext.svjd.videoMontageSVJD.TextAreaDynamic <em>Text Area Dynamic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Text Area Dynamic</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.TextAreaDynamic
   * @generated
   */
  EClass getTextAreaDynamic();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.svjd.videoMontageSVJD.TextAreaDynamic#getTextSrc <em>Text Src</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text Src</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.TextAreaDynamic#getTextSrc()
   * @see #getTextAreaDynamic()
   * @generated
   */
  EAttribute getTextAreaDynamic_TextSrc();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.svjd.videoMontageSVJD.TextAreaDynamic#getLine <em>Line</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Line</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.TextAreaDynamic#getLine()
   * @see #getTextAreaDynamic()
   * @generated
   */
  EAttribute getTextAreaDynamic_Line();

  /**
   * Returns the meta object for class '{@link org.xtext.svjd.videoMontageSVJD.ScrollingText <em>Scrolling Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Scrolling Text</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.ScrollingText
   * @generated
   */
  EClass getScrollingText();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.svjd.videoMontageSVJD.ScrollingText#getSpeed <em>Speed</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Speed</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.ScrollingText#getSpeed()
   * @see #getScrollingText()
   * @generated
   */
  EAttribute getScrollingText_Speed();

  /**
   * Returns the meta object for class '{@link org.xtext.svjd.videoMontageSVJD.FadeIn <em>Fade In</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fade In</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.FadeIn
   * @generated
   */
  EClass getFadeIn();

  /**
   * Returns the meta object for class '{@link org.xtext.svjd.videoMontageSVJD.FadeOut <em>Fade Out</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fade Out</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.FadeOut
   * @generated
   */
  EClass getFadeOut();

  /**
   * Returns the meta object for enum '{@link org.xtext.svjd.videoMontageSVJD.OperationMoment <em>Operation Moment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Operation Moment</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.OperationMoment
   * @generated
   */
  EEnum getOperationMoment();

  /**
   * Returns the meta object for enum '{@link org.xtext.svjd.videoMontageSVJD.Moment <em>Moment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Moment</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.Moment
   * @generated
   */
  EEnum getMoment();

  /**
   * Returns the meta object for enum '{@link org.xtext.svjd.videoMontageSVJD.Color <em>Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Color</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.Color
   * @generated
   */
  EEnum getColor();

  /**
   * Returns the meta object for enum '{@link org.xtext.svjd.videoMontageSVJD.FontStyle <em>Font Style</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Font Style</em>'.
   * @see org.xtext.svjd.videoMontageSVJD.FontStyle
   * @generated
   */
  EEnum getFontStyle();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  VideoMontageSVJDFactory getVideoMontageSVJDFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.svjd.videoMontageSVJD.impl.MovieImpl <em>Movie</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.svjd.videoMontageSVJD.impl.MovieImpl
     * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getMovie()
     * @generated
     */
    EClass MOVIE = eINSTANCE.getMovie();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVIE__TITLE = eINSTANCE.getMovie_Title();

    /**
     * The meta object literal for the '<em><b>Videoelement</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MOVIE__VIDEOELEMENT = eINSTANCE.getMovie_Videoelement();

    /**
     * The meta object literal for the '<em><b>Audioelement</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MOVIE__AUDIOELEMENT = eINSTANCE.getMovie_Audioelement();

    /**
     * The meta object literal for the '<em><b>Subtitle</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MOVIE__SUBTITLE = eINSTANCE.getMovie_Subtitle();

    /**
     * The meta object literal for the '<em><b>Video Timeline</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MOVIE__VIDEO_TIMELINE = eINSTANCE.getMovie_VideoTimeline();

    /**
     * The meta object literal for the '{@link org.xtext.svjd.videoMontageSVJD.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.svjd.videoMontageSVJD.impl.ElementImpl
     * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT__NAME = eINSTANCE.getElement_Name();

    /**
     * The meta object literal for the '{@link org.xtext.svjd.videoMontageSVJD.impl.AudioElementImpl <em>Audio Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.svjd.videoMontageSVJD.impl.AudioElementImpl
     * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getAudioElement()
     * @generated
     */
    EClass AUDIO_ELEMENT = eINSTANCE.getAudioElement();

    /**
     * The meta object literal for the '<em><b>Transition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AUDIO_ELEMENT__TRANSITION = eINSTANCE.getAudioElement_Transition();

    /**
     * The meta object literal for the '{@link org.xtext.svjd.videoMontageSVJD.impl.VideoElementImpl <em>Video Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.svjd.videoMontageSVJD.impl.VideoElementImpl
     * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getVideoElement()
     * @generated
     */
    EClass VIDEO_ELEMENT = eINSTANCE.getVideoElement();

    /**
     * The meta object literal for the '{@link org.xtext.svjd.videoMontageSVJD.impl.VideoTimeLineImpl <em>Video Time Line</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.svjd.videoMontageSVJD.impl.VideoTimeLineImpl
     * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getVideoTimeLine()
     * @generated
     */
    EClass VIDEO_TIME_LINE = eINSTANCE.getVideoTimeLine();

    /**
     * The meta object literal for the '<em><b>Videos</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VIDEO_TIME_LINE__VIDEOS = eINSTANCE.getVideoTimeLine_Videos();

    /**
     * The meta object literal for the '{@link org.xtext.svjd.videoMontageSVJD.impl.TextAreaImpl <em>Text Area</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.svjd.videoMontageSVJD.impl.TextAreaImpl
     * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getTextArea()
     * @generated
     */
    EClass TEXT_AREA = eINSTANCE.getTextArea();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT_AREA__X = eINSTANCE.getTextArea_X();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT_AREA__Y = eINSTANCE.getTextArea_Y();

    /**
     * The meta object literal for the '<em><b>Width</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT_AREA__WIDTH = eINSTANCE.getTextArea_Width();

    /**
     * The meta object literal for the '<em><b>Height</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT_AREA__HEIGHT = eINSTANCE.getTextArea_Height();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT_AREA__TEXT = eINSTANCE.getTextArea_Text();

    /**
     * The meta object literal for the '<em><b>Font</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEXT_AREA__FONT = eINSTANCE.getTextArea_Font();

    /**
     * The meta object literal for the '<em><b>Animation</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEXT_AREA__ANIMATION = eINSTANCE.getTextArea_Animation();

    /**
     * The meta object literal for the '{@link org.xtext.svjd.videoMontageSVJD.impl.StartingMomentImpl <em>Starting Moment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.svjd.videoMontageSVJD.impl.StartingMomentImpl
     * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getStartingMoment()
     * @generated
     */
    EClass STARTING_MOMENT = eINSTANCE.getStartingMoment();

    /**
     * The meta object literal for the '{@link org.xtext.svjd.videoMontageSVJD.impl.AnimationImpl <em>Animation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.svjd.videoMontageSVJD.impl.AnimationImpl
     * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getAnimation()
     * @generated
     */
    EClass ANIMATION = eINSTANCE.getAnimation();

    /**
     * The meta object literal for the '<em><b>Duration</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ANIMATION__DURATION = eINSTANCE.getAnimation_Duration();

    /**
     * The meta object literal for the '{@link org.xtext.svjd.videoMontageSVJD.impl.SubtitleImpl <em>Subtitle</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.svjd.videoMontageSVJD.impl.SubtitleImpl
     * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getSubtitle()
     * @generated
     */
    EClass SUBTITLE = eINSTANCE.getSubtitle();

    /**
     * The meta object literal for the '<em><b>Startingmoment</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUBTITLE__STARTINGMOMENT = eINSTANCE.getSubtitle_Startingmoment();

    /**
     * The meta object literal for the '<em><b>Duration</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUBTITLE__DURATION = eINSTANCE.getSubtitle_Duration();

    /**
     * The meta object literal for the '<em><b>Textarea</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUBTITLE__TEXTAREA = eINSTANCE.getSubtitle_Textarea();

    /**
     * The meta object literal for the '{@link org.xtext.svjd.videoMontageSVJD.impl.AudioImpl <em>Audio</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.svjd.videoMontageSVJD.impl.AudioImpl
     * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getAudio()
     * @generated
     */
    EClass AUDIO = eINSTANCE.getAudio();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AUDIO__PATH = eINSTANCE.getAudio_Path();

    /**
     * The meta object literal for the '{@link org.xtext.svjd.videoMontageSVJD.impl.AudioClipImpl <em>Audio Clip</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.svjd.videoMontageSVJD.impl.AudioClipImpl
     * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getAudioClip()
     * @generated
     */
    EClass AUDIO_CLIP = eINSTANCE.getAudioClip();

    /**
     * The meta object literal for the '<em><b>Startingmoment</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AUDIO_CLIP__STARTINGMOMENT = eINSTANCE.getAudioClip_Startingmoment();

    /**
     * The meta object literal for the '<em><b>Volume</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AUDIO_CLIP__VOLUME = eINSTANCE.getAudioClip_Volume();

    /**
     * The meta object literal for the '<em><b>Start Cut</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AUDIO_CLIP__START_CUT = eINSTANCE.getAudioClip_StartCut();

    /**
     * The meta object literal for the '<em><b>End Cut</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AUDIO_CLIP__END_CUT = eINSTANCE.getAudioClip_EndCut();

    /**
     * The meta object literal for the '<em><b>Audio</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AUDIO_CLIP__AUDIO = eINSTANCE.getAudioClip_Audio();

    /**
     * The meta object literal for the '{@link org.xtext.svjd.videoMontageSVJD.impl.ClipImpl <em>Clip</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.svjd.videoMontageSVJD.impl.ClipImpl
     * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getClip()
     * @generated
     */
    EClass CLIP = eINSTANCE.getClip();

    /**
     * The meta object literal for the '<em><b>Start Cut</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLIP__START_CUT = eINSTANCE.getClip_StartCut();

    /**
     * The meta object literal for the '<em><b>End Cut</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLIP__END_CUT = eINSTANCE.getClip_EndCut();

    /**
     * The meta object literal for the '<em><b>Video</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLIP__VIDEO = eINSTANCE.getClip_Video();

    /**
     * The meta object literal for the '{@link org.xtext.svjd.videoMontageSVJD.impl.TitleImpl <em>Title</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.svjd.videoMontageSVJD.impl.TitleImpl
     * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getTitle()
     * @generated
     */
    EClass TITLE = eINSTANCE.getTitle();

    /**
     * The meta object literal for the '<em><b>Duration</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TITLE__DURATION = eINSTANCE.getTitle_Duration();

    /**
     * The meta object literal for the '<em><b>Background Color</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TITLE__BACKGROUND_COLOR = eINSTANCE.getTitle_BackgroundColor();

    /**
     * The meta object literal for the '<em><b>Textarea</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TITLE__TEXTAREA = eINSTANCE.getTitle_Textarea();

    /**
     * The meta object literal for the '{@link org.xtext.svjd.videoMontageSVJD.impl.VideoImpl <em>Video</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.svjd.videoMontageSVJD.impl.VideoImpl
     * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getVideo()
     * @generated
     */
    EClass VIDEO = eINSTANCE.getVideo();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VIDEO__PATH = eINSTANCE.getVideo_Path();

    /**
     * The meta object literal for the '{@link org.xtext.svjd.videoMontageSVJD.impl.RelativeMomentImpl <em>Relative Moment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.svjd.videoMontageSVJD.impl.RelativeMomentImpl
     * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getRelativeMoment()
     * @generated
     */
    EClass RELATIVE_MOMENT = eINSTANCE.getRelativeMoment();

    /**
     * The meta object literal for the '<em><b>Moment</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RELATIVE_MOMENT__MOMENT = eINSTANCE.getRelativeMoment_Moment();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATIVE_MOMENT__ELEMENT = eINSTANCE.getRelativeMoment_Element();

    /**
     * The meta object literal for the '<em><b>Operation Moment</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RELATIVE_MOMENT__OPERATION_MOMENT = eINSTANCE.getRelativeMoment_OperationMoment();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RELATIVE_MOMENT__VALUE = eINSTANCE.getRelativeMoment_Value();

    /**
     * The meta object literal for the '{@link org.xtext.svjd.videoMontageSVJD.impl.AbsoluteMomentImpl <em>Absolute Moment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.svjd.videoMontageSVJD.impl.AbsoluteMomentImpl
     * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getAbsoluteMoment()
     * @generated
     */
    EClass ABSOLUTE_MOMENT = eINSTANCE.getAbsoluteMoment();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ABSOLUTE_MOMENT__TIME = eINSTANCE.getAbsoluteMoment_Time();

    /**
     * The meta object literal for the '{@link org.xtext.svjd.videoMontageSVJD.impl.TransitionImpl <em>Transition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.svjd.videoMontageSVJD.impl.TransitionImpl
     * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getTransition()
     * @generated
     */
    EClass TRANSITION = eINSTANCE.getTransition();

    /**
     * The meta object literal for the '<em><b>Duration</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRANSITION__DURATION = eINSTANCE.getTransition_Duration();

    /**
     * The meta object literal for the '<em><b>Audioelement</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION__AUDIOELEMENT = eINSTANCE.getTransition_Audioelement();

    /**
     * The meta object literal for the '{@link org.xtext.svjd.videoMontageSVJD.impl.FontImpl <em>Font</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.svjd.videoMontageSVJD.impl.FontImpl
     * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getFont()
     * @generated
     */
    EClass FONT = eINSTANCE.getFont();

    /**
     * The meta object literal for the '<em><b>Font Style</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FONT__FONT_STYLE = eINSTANCE.getFont_FontStyle();

    /**
     * The meta object literal for the '<em><b>Length</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FONT__LENGTH = eINSTANCE.getFont_Length();

    /**
     * The meta object literal for the '{@link org.xtext.svjd.videoMontageSVJD.impl.TextAreaDynamicImpl <em>Text Area Dynamic</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.svjd.videoMontageSVJD.impl.TextAreaDynamicImpl
     * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getTextAreaDynamic()
     * @generated
     */
    EClass TEXT_AREA_DYNAMIC = eINSTANCE.getTextAreaDynamic();

    /**
     * The meta object literal for the '<em><b>Text Src</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT_AREA_DYNAMIC__TEXT_SRC = eINSTANCE.getTextAreaDynamic_TextSrc();

    /**
     * The meta object literal for the '<em><b>Line</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT_AREA_DYNAMIC__LINE = eINSTANCE.getTextAreaDynamic_Line();

    /**
     * The meta object literal for the '{@link org.xtext.svjd.videoMontageSVJD.impl.ScrollingTextImpl <em>Scrolling Text</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.svjd.videoMontageSVJD.impl.ScrollingTextImpl
     * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getScrollingText()
     * @generated
     */
    EClass SCROLLING_TEXT = eINSTANCE.getScrollingText();

    /**
     * The meta object literal for the '<em><b>Speed</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCROLLING_TEXT__SPEED = eINSTANCE.getScrollingText_Speed();

    /**
     * The meta object literal for the '{@link org.xtext.svjd.videoMontageSVJD.impl.FadeInImpl <em>Fade In</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.svjd.videoMontageSVJD.impl.FadeInImpl
     * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getFadeIn()
     * @generated
     */
    EClass FADE_IN = eINSTANCE.getFadeIn();

    /**
     * The meta object literal for the '{@link org.xtext.svjd.videoMontageSVJD.impl.FadeOutImpl <em>Fade Out</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.svjd.videoMontageSVJD.impl.FadeOutImpl
     * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getFadeOut()
     * @generated
     */
    EClass FADE_OUT = eINSTANCE.getFadeOut();

    /**
     * The meta object literal for the '{@link org.xtext.svjd.videoMontageSVJD.OperationMoment <em>Operation Moment</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.svjd.videoMontageSVJD.OperationMoment
     * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getOperationMoment()
     * @generated
     */
    EEnum OPERATION_MOMENT = eINSTANCE.getOperationMoment();

    /**
     * The meta object literal for the '{@link org.xtext.svjd.videoMontageSVJD.Moment <em>Moment</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.svjd.videoMontageSVJD.Moment
     * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getMoment()
     * @generated
     */
    EEnum MOMENT = eINSTANCE.getMoment();

    /**
     * The meta object literal for the '{@link org.xtext.svjd.videoMontageSVJD.Color <em>Color</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.svjd.videoMontageSVJD.Color
     * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getColor()
     * @generated
     */
    EEnum COLOR = eINSTANCE.getColor();

    /**
     * The meta object literal for the '{@link org.xtext.svjd.videoMontageSVJD.FontStyle <em>Font Style</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.svjd.videoMontageSVJD.FontStyle
     * @see org.xtext.svjd.videoMontageSVJD.impl.VideoMontageSVJDPackageImpl#getFontStyle()
     * @generated
     */
    EEnum FONT_STYLE = eINSTANCE.getFontStyle();

  }

} //VideoMontageSVJDPackage
