/*
 * generated by Xtext 2.24.0
 */
package org.xtext.svjd.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.svjd.ide.contentassist.antlr.internal.InternalVideoMontageParser;
import org.xtext.svjd.services.VideoMontageGrammarAccess;

public class VideoMontageParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(VideoMontageGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, VideoMontageGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getAudioElementAccess().getAlternatives_1(), "rule__AudioElement__Alternatives_1");
			builder.put(grammarAccess.getVideoElementAccess().getAlternatives_1(), "rule__VideoElement__Alternatives_1");
			builder.put(grammarAccess.getTextAreaAccess().getAlternatives(), "rule__TextArea__Alternatives");
			builder.put(grammarAccess.getStartingMomentAccess().getAlternatives(), "rule__StartingMoment__Alternatives");
			builder.put(grammarAccess.getAnimationAccess().getAlternatives(), "rule__Animation__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEDoubleAccess().getAlternatives_4_0(), "rule__EDouble__Alternatives_4_0");
			builder.put(grammarAccess.getOperationMomentAccess().getAlternatives(), "rule__OperationMoment__Alternatives");
			builder.put(grammarAccess.getMomentAccess().getAlternatives(), "rule__Moment__Alternatives");
			builder.put(grammarAccess.getMovieAccess().getGroup(), "rule__Movie__Group__0");
			builder.put(grammarAccess.getMovieAccess().getGroup_5(), "rule__Movie__Group_5__0");
			builder.put(grammarAccess.getMovieAccess().getGroup_6(), "rule__Movie__Group_6__0");
			builder.put(grammarAccess.getAudioElementAccess().getGroup(), "rule__AudioElement__Group__0");
			builder.put(grammarAccess.getVideoElementAccess().getGroup(), "rule__VideoElement__Group__0");
			builder.put(grammarAccess.getVideoTimeLineAccess().getGroup(), "rule__VideoTimeLine__Group__0");
			builder.put(grammarAccess.getSubtitleAccess().getGroup(), "rule__Subtitle__Group__0");
			builder.put(grammarAccess.getSubtitleAccess().getGroup_6(), "rule__Subtitle__Group_6__0");
			builder.put(grammarAccess.getAudioAccess().getGroup(), "rule__Audio__Group__0");
			builder.put(grammarAccess.getAudioAccess().getGroup_6(), "rule__Audio__Group_6__0");
			builder.put(grammarAccess.getAudioAccess().getGroup_7(), "rule__Audio__Group_7__0");
			builder.put(grammarAccess.getAudioClipAccess().getGroup(), "rule__AudioClip__Group__0");
			builder.put(grammarAccess.getAudioClipAccess().getGroup_6(), "rule__AudioClip__Group_6__0");
			builder.put(grammarAccess.getAudioClipAccess().getGroup_7(), "rule__AudioClip__Group_7__0");
			builder.put(grammarAccess.getAudioClipAccess().getGroup_8(), "rule__AudioClip__Group_8__0");
			builder.put(grammarAccess.getAudioClipAccess().getGroup_9(), "rule__AudioClip__Group_9__0");
			builder.put(grammarAccess.getClipAccess().getGroup(), "rule__Clip__Group__0");
			builder.put(grammarAccess.getClipAccess().getGroup_3(), "rule__Clip__Group_3__0");
			builder.put(grammarAccess.getClipAccess().getGroup_4(), "rule__Clip__Group_4__0");
			builder.put(grammarAccess.getTitleAccess().getGroup(), "rule__Title__Group__0");
			builder.put(grammarAccess.getTitleAccess().getGroup_3(), "rule__Title__Group_3__0");
			builder.put(grammarAccess.getTitleAccess().getGroup_4(), "rule__Title__Group_4__0");
			builder.put(grammarAccess.getVideoAccess().getGroup(), "rule__Video__Group__0");
			builder.put(grammarAccess.getVideoAccess().getGroup_1(), "rule__Video__Group_1__0");
			builder.put(grammarAccess.getRelativeMomentAccess().getGroup(), "rule__RelativeMoment__Group__0");
			builder.put(grammarAccess.getRelativeMomentAccess().getGroup_4(), "rule__RelativeMoment__Group_4__0");
			builder.put(grammarAccess.getAbsoluteMomentAccess().getGroup(), "rule__AbsoluteMoment__Group__0");
			builder.put(grammarAccess.getAbsoluteMomentAccess().getGroup_1(), "rule__AbsoluteMoment__Group_1__0");
			builder.put(grammarAccess.getStartingMoment_ImplAccess().getGroup(), "rule__StartingMoment_Impl__Group__0");
			builder.put(grammarAccess.getTransitionAccess().getGroup(), "rule__Transition__Group__0");
			builder.put(grammarAccess.getTransitionAccess().getGroup_2(), "rule__Transition__Group_2__0");
			builder.put(grammarAccess.getTextArea_ImplAccess().getGroup(), "rule__TextArea_Impl__Group__0");
			builder.put(grammarAccess.getTextArea_ImplAccess().getGroup_2(), "rule__TextArea_Impl__Group_2__0");
			builder.put(grammarAccess.getTextArea_ImplAccess().getGroup_3(), "rule__TextArea_Impl__Group_3__0");
			builder.put(grammarAccess.getTextArea_ImplAccess().getGroup_4(), "rule__TextArea_Impl__Group_4__0");
			builder.put(grammarAccess.getTextArea_ImplAccess().getGroup_5(), "rule__TextArea_Impl__Group_5__0");
			builder.put(grammarAccess.getTextArea_ImplAccess().getGroup_6(), "rule__TextArea_Impl__Group_6__0");
			builder.put(grammarAccess.getTextArea_ImplAccess().getGroup_7(), "rule__TextArea_Impl__Group_7__0");
			builder.put(grammarAccess.getTextArea_ImplAccess().getGroup_8(), "rule__TextArea_Impl__Group_8__0");
			builder.put(grammarAccess.getFontAccess().getGroup(), "rule__Font__Group__0");
			builder.put(grammarAccess.getFontAccess().getGroup_2(), "rule__Font__Group_2__0");
			builder.put(grammarAccess.getTextAreaDynamicAccess().getGroup(), "rule__TextAreaDynamic__Group__0");
			builder.put(grammarAccess.getTextAreaDynamicAccess().getGroup_2(), "rule__TextAreaDynamic__Group_2__0");
			builder.put(grammarAccess.getTextAreaDynamicAccess().getGroup_3(), "rule__TextAreaDynamic__Group_3__0");
			builder.put(grammarAccess.getTextAreaDynamicAccess().getGroup_4(), "rule__TextAreaDynamic__Group_4__0");
			builder.put(grammarAccess.getTextAreaDynamicAccess().getGroup_5(), "rule__TextAreaDynamic__Group_5__0");
			builder.put(grammarAccess.getTextAreaDynamicAccess().getGroup_6(), "rule__TextAreaDynamic__Group_6__0");
			builder.put(grammarAccess.getTextAreaDynamicAccess().getGroup_7(), "rule__TextAreaDynamic__Group_7__0");
			builder.put(grammarAccess.getTextAreaDynamicAccess().getGroup_8(), "rule__TextAreaDynamic__Group_8__0");
			builder.put(grammarAccess.getTextAreaDynamicAccess().getGroup_11(), "rule__TextAreaDynamic__Group_11__0");
			builder.put(grammarAccess.getFadeInAccess().getGroup(), "rule__FadeIn__Group__0");
			builder.put(grammarAccess.getFadeInAccess().getGroup_3(), "rule__FadeIn__Group_3__0");
			builder.put(grammarAccess.getFadeOutAccess().getGroup(), "rule__FadeOut__Group__0");
			builder.put(grammarAccess.getFadeOutAccess().getGroup_3(), "rule__FadeOut__Group_3__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup(), "rule__EDouble__Group__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup_4(), "rule__EDouble__Group_4__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getMovieAccess().getTitleAssignment_1(), "rule__Movie__TitleAssignment_1");
			builder.put(grammarAccess.getMovieAccess().getVideoelementAssignment_3(), "rule__Movie__VideoelementAssignment_3");
			builder.put(grammarAccess.getMovieAccess().getVideoelementAssignment_4(), "rule__Movie__VideoelementAssignment_4");
			builder.put(grammarAccess.getMovieAccess().getAudioelementAssignment_5_0(), "rule__Movie__AudioelementAssignment_5_0");
			builder.put(grammarAccess.getMovieAccess().getAudioelementAssignment_5_1(), "rule__Movie__AudioelementAssignment_5_1");
			builder.put(grammarAccess.getMovieAccess().getSubtitleAssignment_6_0(), "rule__Movie__SubtitleAssignment_6_0");
			builder.put(grammarAccess.getMovieAccess().getSubtitleAssignment_6_1(), "rule__Movie__SubtitleAssignment_6_1");
			builder.put(grammarAccess.getMovieAccess().getVideoTimelineAssignment_7(), "rule__Movie__VideoTimelineAssignment_7");
			builder.put(grammarAccess.getVideoTimeLineAccess().getVideosAssignment_1(), "rule__VideoTimeLine__VideosAssignment_1");
			builder.put(grammarAccess.getVideoTimeLineAccess().getVideosAssignment_2(), "rule__VideoTimeLine__VideosAssignment_2");
			builder.put(grammarAccess.getSubtitleAccess().getNameAssignment_1(), "rule__Subtitle__NameAssignment_1");
			builder.put(grammarAccess.getSubtitleAccess().getStartingmomentAssignment_4(), "rule__Subtitle__StartingmomentAssignment_4");
			builder.put(grammarAccess.getSubtitleAccess().getDurationAssignment_6_1(), "rule__Subtitle__DurationAssignment_6_1");
			builder.put(grammarAccess.getSubtitleAccess().getTextareaAssignment_8(), "rule__Subtitle__TextareaAssignment_8");
			builder.put(grammarAccess.getAudioAccess().getNameAssignment_1(), "rule__Audio__NameAssignment_1");
			builder.put(grammarAccess.getAudioAccess().getStartingmomentAssignment_4(), "rule__Audio__StartingmomentAssignment_4");
			builder.put(grammarAccess.getAudioAccess().getPathAssignment_6_1(), "rule__Audio__PathAssignment_6_1");
			builder.put(grammarAccess.getAudioAccess().getTransitionAssignment_7_1(), "rule__Audio__TransitionAssignment_7_1");
			builder.put(grammarAccess.getAudioClipAccess().getNameAssignment_1(), "rule__AudioClip__NameAssignment_1");
			builder.put(grammarAccess.getAudioClipAccess().getStartingmomentAssignment_4(), "rule__AudioClip__StartingmomentAssignment_4");
			builder.put(grammarAccess.getAudioClipAccess().getVolumeAssignment_6_1(), "rule__AudioClip__VolumeAssignment_6_1");
			builder.put(grammarAccess.getAudioClipAccess().getStartCutAssignment_7_1(), "rule__AudioClip__StartCutAssignment_7_1");
			builder.put(grammarAccess.getAudioClipAccess().getEndCutAssignment_8_1(), "rule__AudioClip__EndCutAssignment_8_1");
			builder.put(grammarAccess.getAudioClipAccess().getTransitionAssignment_9_1(), "rule__AudioClip__TransitionAssignment_9_1");
			builder.put(grammarAccess.getAudioClipAccess().getAudioAssignment_11(), "rule__AudioClip__AudioAssignment_11");
			builder.put(grammarAccess.getClipAccess().getNameAssignment_1(), "rule__Clip__NameAssignment_1");
			builder.put(grammarAccess.getClipAccess().getStartCutAssignment_3_1(), "rule__Clip__StartCutAssignment_3_1");
			builder.put(grammarAccess.getClipAccess().getEndCutAssignment_4_1(), "rule__Clip__EndCutAssignment_4_1");
			builder.put(grammarAccess.getClipAccess().getVideoAssignment_6(), "rule__Clip__VideoAssignment_6");
			builder.put(grammarAccess.getTitleAccess().getNameAssignment_1(), "rule__Title__NameAssignment_1");
			builder.put(grammarAccess.getTitleAccess().getDurationAssignment_3_1(), "rule__Title__DurationAssignment_3_1");
			builder.put(grammarAccess.getTitleAccess().getBackgroundColorAssignment_4_1(), "rule__Title__BackgroundColorAssignment_4_1");
			builder.put(grammarAccess.getTitleAccess().getTextareaAssignment_6(), "rule__Title__TextareaAssignment_6");
			builder.put(grammarAccess.getVideoAccess().getNameAssignment_0(), "rule__Video__NameAssignment_0");
			builder.put(grammarAccess.getVideoAccess().getPathAssignment_1_1(), "rule__Video__PathAssignment_1_1");
			builder.put(grammarAccess.getRelativeMomentAccess().getMomentAssignment_1(), "rule__RelativeMoment__MomentAssignment_1");
			builder.put(grammarAccess.getRelativeMomentAccess().getElementAssignment_3(), "rule__RelativeMoment__ElementAssignment_3");
			builder.put(grammarAccess.getRelativeMomentAccess().getOperationMomentAssignment_4_0(), "rule__RelativeMoment__OperationMomentAssignment_4_0");
			builder.put(grammarAccess.getRelativeMomentAccess().getValueAssignment_4_1(), "rule__RelativeMoment__ValueAssignment_4_1");
			builder.put(grammarAccess.getAbsoluteMomentAccess().getTimeAssignment_1_1(), "rule__AbsoluteMoment__TimeAssignment_1_1");
			builder.put(grammarAccess.getTransitionAccess().getDurationAssignment_2_1(), "rule__Transition__DurationAssignment_2_1");
			builder.put(grammarAccess.getTransitionAccess().getAudioelementAssignment_4(), "rule__Transition__AudioelementAssignment_4");
			builder.put(grammarAccess.getTextArea_ImplAccess().getXAssignment_2_1(), "rule__TextArea_Impl__XAssignment_2_1");
			builder.put(grammarAccess.getTextArea_ImplAccess().getYAssignment_3_1(), "rule__TextArea_Impl__YAssignment_3_1");
			builder.put(grammarAccess.getTextArea_ImplAccess().getWidthAssignment_4_1(), "rule__TextArea_Impl__WidthAssignment_4_1");
			builder.put(grammarAccess.getTextArea_ImplAccess().getHeightAssignment_5_1(), "rule__TextArea_Impl__HeightAssignment_5_1");
			builder.put(grammarAccess.getTextArea_ImplAccess().getTextAssignment_6_1(), "rule__TextArea_Impl__TextAssignment_6_1");
			builder.put(grammarAccess.getTextArea_ImplAccess().getFontAssignment_7_1(), "rule__TextArea_Impl__FontAssignment_7_1");
			builder.put(grammarAccess.getTextArea_ImplAccess().getAnimationAssignment_8_1(), "rule__TextArea_Impl__AnimationAssignment_8_1");
			builder.put(grammarAccess.getTextArea_ImplAccess().getAnimationAssignment_8_2(), "rule__TextArea_Impl__AnimationAssignment_8_2");
			builder.put(grammarAccess.getFontAccess().getFontStyleAssignment_1(), "rule__Font__FontStyleAssignment_1");
			builder.put(grammarAccess.getFontAccess().getLengthAssignment_2_1(), "rule__Font__LengthAssignment_2_1");
			builder.put(grammarAccess.getTextAreaDynamicAccess().getXAssignment_2_1(), "rule__TextAreaDynamic__XAssignment_2_1");
			builder.put(grammarAccess.getTextAreaDynamicAccess().getYAssignment_3_1(), "rule__TextAreaDynamic__YAssignment_3_1");
			builder.put(grammarAccess.getTextAreaDynamicAccess().getWidthAssignment_4_1(), "rule__TextAreaDynamic__WidthAssignment_4_1");
			builder.put(grammarAccess.getTextAreaDynamicAccess().getHeightAssignment_5_1(), "rule__TextAreaDynamic__HeightAssignment_5_1");
			builder.put(grammarAccess.getTextAreaDynamicAccess().getTextAssignment_6_1(), "rule__TextAreaDynamic__TextAssignment_6_1");
			builder.put(grammarAccess.getTextAreaDynamicAccess().getTextSrcAssignment_7_1(), "rule__TextAreaDynamic__TextSrcAssignment_7_1");
			builder.put(grammarAccess.getTextAreaDynamicAccess().getLineAssignment_8_1(), "rule__TextAreaDynamic__LineAssignment_8_1");
			builder.put(grammarAccess.getTextAreaDynamicAccess().getFontAssignment_10(), "rule__TextAreaDynamic__FontAssignment_10");
			builder.put(grammarAccess.getTextAreaDynamicAccess().getAnimationAssignment_11_1(), "rule__TextAreaDynamic__AnimationAssignment_11_1");
			builder.put(grammarAccess.getTextAreaDynamicAccess().getAnimationAssignment_11_2(), "rule__TextAreaDynamic__AnimationAssignment_11_2");
			builder.put(grammarAccess.getFadeInAccess().getDurationAssignment_3_1(), "rule__FadeIn__DurationAssignment_3_1");
			builder.put(grammarAccess.getFadeOutAccess().getDurationAssignment_3_1(), "rule__FadeOut__DurationAssignment_3_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private VideoMontageGrammarAccess grammarAccess;

	@Override
	protected InternalVideoMontageParser createParser() {
		InternalVideoMontageParser result = new InternalVideoMontageParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public VideoMontageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(VideoMontageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
