/*
 * generated by Xtext 2.24.0
 */
package org.xtext.svjd.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractVideoMontageSVJDValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.xtext.svjd.videoMontageSVJD.VideoMontageSVJDPackage.eINSTANCE);
		return result;
	}
}
