/**
 *
 * $Id$
 */
package VideoMontage.validation;

import VideoMontage.StartingMoment;
import VideoMontage.TextArea;

/**
 * A sample validator interface for {@link VideoMontage.Subtitle}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SubtitleValidator {
	boolean validate();

	boolean validateTextarea(TextArea value);
	boolean validateStartingmoment(StartingMoment value);
}
