/**
 *
 * $Id$
 */
package VideoMontage.validation;

import VideoMontage.Animation;
import VideoMontage.Font;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link VideoMontage.TextArea}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TextAreaValidator {
	boolean validate();

	boolean validateX(int value);
	boolean validateY(int value);
	boolean validateWidth(double value);
	boolean validateHeight(double value);
	boolean validateText(String value);
	boolean validateFont(Font value);
	boolean validateAnimation(EList<Animation> value);
}
