/**
 *
 * $Id$
 */
package VideoMontage.validation;

import VideoMontage.Color;
import VideoMontage.TextArea;

/**
 * A sample validator interface for {@link VideoMontage.Title}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TitleValidator {
	boolean validate();

	boolean validateTextarea(TextArea value);
	boolean validateBackgroundColor(Color value);

	boolean validateName(String value);
}
