/*
 * generated by Xtext 2.24.0
 */
package org.xtext.svjd.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class VideoMontageSVJDAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/svjd/parser/antlr/internal/InternalVideoMontageSVJD.tokens");
	}
}
